### ISSUE TITLE
[BUG] GUI trainer "v_1_1.wav" does not match any known standard input files

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#103]
Just tried the NAM GUI trainer and got the error in the title. Maybe the lengthy path  - will retry with a shorter one too

![image](https://user-images.githubusercontent.com/125308373/221409946-eba785a4-3981-49a8-85a4-f5dfdec00d14.png)

Training via CLI with the dry & wet files in the root folder works fine.

![image](https://user-images.githubusercontent.com/125308373/221410158-4b2b69ab-ba53-4444-a8d1-0cbbeada7c87.png)

**Comment by sdatkinson** [comment]
Can you paste the full file names?

**Comment by jolappi** [comment]
He is using other tha v1_1_1.wav and thats why ui is not complying.

There was question in the fb for this that could there be like checkbox in advanced settings that you could then use any input source with gui?

Thanks and by the way nice work.

**Comment by PrimalNerd** [comment]
I get the same error with v1_1_1.wav
I get a md5 hash that differs from the one in nam/train/core.py. If I add the md5 hash to versions it lets me use the file and starts training.

**Comment by sdatkinson** [comment]
I've added "weak matching" in #220, which should allow folks to "hack" the training file without getting themselves into too much trouble. Will be in the next release 👍🏻
