### ISSUE TITLE
Improve training on M1 Macs utilizing METAL

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#104]
Allow M1 Macs to unleash their full power on training models using METAL

**Comment by sdatkinson** [comment]
Notes to self:
* [`torch.backends`](https://pytorch.org/docs/stable/backends.html)
* [`torch.backends.mps.is_available`](https://pytorch.org/docs/stable/backends.html#torch.backends.mps.is_available)
* [`torch.backends.mps.is_built`](https://pytorch.org/docs/stable/backends.html#torch.backends.mps.is_built)

**Comment by 2-dor** [comment]
> Allow M1 Macs to unleash their full power on training models using METAL

METAL \m/
