### ISSUE TITLE
CTRL + C Doesn'[BUG]

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/neural-amp-modeler#105]
Hi there. When I hit CTRL + C on Windows while training a model, Torch and Python shut down and I don't get a model saved. It would be great to be able to cancel training early if the ESR is at acceptable levels. 

I'm running Windows 10 - NVIDIA 3050 laptop GPU - Intel I7

**Comment by 2-dor** [comment]
> Hi there. When I hit CTRL + C on Windows while training a model, Torch and Python shut down and I don't get a model saved. It would be great to be able to cancel training early if the ESR is at acceptable levels.
> 
> I'm running Windows 10 - NVIDIA 3050 laptop GPU - Intel I7

Good point. It would be nice to have a break sequence that could just spit out the model.

**Comment by sdatkinson** [comment]
Hmm. This is odd--it used to do a graceful shutdown. I'd be grateful if you did some Googling about PyTorch Lightning's Graceful shutdown and see if it's something they changed?

**Comment by vossenv** [comment]
I can confirm this happens to me as well

**Comment by sdatkinson** [comment]
I think I got it. Sit tight.
