### ISSUE TITLE
GPU support with a Mac M1/M2 - Apple Silicon

### ISSUE THREAD

**Issue by ncsolar** [sdatkinson/neural-amp-modeler#107]
Please implement: 

Tensorflow-metal  [https://developer.apple.com/metal/tensorflow-plugin/](https://developer.apple.com/metal/tensorflow-plugin/)

To be able to accelerate the training of NAM models with TensorFlow on a Apple Silicon M1/M2 processor.

**Comment by sdatkinson** [comment]
Duplicate of #104
