### ISSUE TITLE
[FEATURE] Squash models to reduce size by 1/3

### ISSUE THREAD

**Issue by GuitarML** [sdatkinson/neural-amp-modeler#108]
This is more of a suggestion than a feature, but you can reduce the model file size by about 1/3 by squashing the json format to a single line. I did a quick test and it loads fine in NAM. It might not be a big deal now, but when the model repo gets bigger it would be helpful when users are downloading/uploading, and it's an easy thing to implement. I'll attach the example model I "squashed" and the original I tested in the NAM plugin:
[sovtek_mig50.zip](https://github.com/sdatkinson/neural-amp-modeler/files/10860628/sovtek_mig50.zip)

The squashed is 276 KB vs the original 412 KB

**Comment by sdatkinson** [comment]
Good call. I believe there's an `indent` in the `json.dump` that should do the trick if removed.

**Comment by mikeoliphant** [comment]
Or maybe support a binary format as well?

**Comment by sdatkinson** [comment]
Yep, that'd be fine.
