### ISSUE TITLE
Xcode compilation error for iOS auv3

### ISSUE THREAD

**Issue by demym** [sdatkinson/neural-amp-modeler#109]
Hi,

first of all thanks for this great project, I tried it recently and sounds absolutely awesome !!

I am a developer myself, and I and trying to compile the iOS auv3 plugin, but I get errors in Xcode (using Xcode14).

First of all, in the repository there's an 'Eigen' folder, but its content is empty. What version of Eigen exactly does it needs ? Same for iplug folder, but in that case the iplug repository gets correctly linked here on GitHub.

I attached a screenshot with the errors I get compiling in XCODE:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/13074812/222376908-14369aa6-c83e-49a9-b02b-54af29b0a46f.png">

Thanks very much in advance and compliments again for the great work !!!

**Comment by sdatkinson** [comment]
Hi! This looks like this belongs over in [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin). Mind submitting there?
