### ISSUE TITLE
Faster training with mac M2(maybe M1)

### ISSUE THREAD

**Issue by jolappi** [sdatkinson/neural-amp-modeler#110]
You can speedup M2 training by changing/adding few parameters (bolded) in file nam/train/core.py
    learning_config = {
        "train_dataloader": {
            **"batch_size": 64,**
            "shuffle": True,
            "pin_memory": True,
            "drop_last": True,
            "num_workers": 0,
        },
        "val_dataloader": {},
        "trainer": {**"accelerator":"mps",**"max_epochs": epochs, **device_config},

Same changes applies to corresponding json used with cli

**Comment by 2-dor** [comment]
> 

Does this affect accuracy? IE. if you train the same model (same output.wav and v1_1_1.wav file pair) with the batch_siez set to default (16) and 64?

**Comment by jolappi** [comment]
No it doesn't but now that it's faster you can use the advanced setting to add more epoch's to get more accuracy with cost of consuming more time training.
Basically if your increase epochs ex. 100->200 you get 0.015 more accurate signal then it start to effect less for every hundred you increase.

**Comment by sdatkinson** [comment]
@jolappi , this is almost the fix. If you can write the code to check what system it's running on, then I'd love a PR for this 😄 

I'm going to close this as a duplicate to #104. We can continue there.
