### ISSUE TITLE
Change request - NAM Trainer GUI - Add a button that will interrupt training and complete process (deliver a .nam file)

### ISSUE THREAD

**Issue by JZ1978** [sdatkinson/neural-amp-modeler#117]
Can we somehow add a button to this that would stop the trainer at the next possible Epoch completion and then proceed to finalize the process from there (and deliver the ESR graph and .nam file)? 

The use case would be when you set up a 1,000 Epoch training session and at some point you see your Checkpoints reporting a super low ESR already, so you just want to end it.

**Comment by sdatkinson** [comment]
Resolved by #118

**Comment by JZ1978** [comment]
Aw heck yea!
