### ISSUE TITLE
[FEATURE] Local Training with AMD cards

### ISSUE THREAD

**Issue by danielriosantos** [sdatkinson/neural-amp-modeler#120]
Hi, is there any chance of improving training speed for computers equipped with AMD cards?

Thanks for your hard work.

**Comment by sdatkinson** [comment]
Unfortunately, this falls under the PyTorch library's support.  Once (if) they support AMD GPUs, then I might with NAM.

So I'm going to mark this as a "wontfix", but please let me know if this changes--I'd be happy to support then!

**Comment by dhgouveia2** [comment]
Adding these two commands before cloning the repository `!pip install git+https://github.com/sdatkinson/neural-amp-modeler.git@main`, worked for me, in Ubuntu 22.04 and AMD 6700XT

```python
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
```
```python
!pip install tensorflow-rocm 
```

![image](https://user-images.githubusercontent.com/24292467/227522560-2807ec92-7c87-4f0e-935b-cad9b89a0966.png)

![image](https://user-images.githubusercontent.com/24292467/227522721-06b81289-dade-40d6-9338-643290ea94b4.png)

```bash
$ rocm-smi


======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK     MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
0    56.0c           89.0W   2605Mhz  1000Mhz  14.12%  auto  211.0W   12%   99%   
================================================================================
============================= End of ROCm SMI Log ==============================
```

**Comment by mikeoliphant** [comment]
I tried getting this to work on Windows (WSL2 running Ubuntu) and it ran but didn't see my GPU.

I'm guessing graphics drivers need to be installed? Any insights on extra steps necessary to get this working from scratch would be much appreciated.
