### ISSUE TITLE
Nam share[FEATURE]

### ISSUE THREAD

**Issue by jolappi** [sdatkinson/neural-amp-modeler#121]
I made little demo for nam sharing with firebase/html/javascript as open source and i was wondering if you know anyone who would continue from that. Here’s link to code https://github.com/jolappi/stainedwithblood/blob/master/namshare.html and here’s testing site https://stainedblood.com/namshare.html

**Comment by 38github** [comment]
How did you profile with Convnet and not WaveNet? By the way, I uploaded a .nam file to your web site.

**Comment by jolappi** [comment]
Only change i have made is for mac 'accelerator':'mps', maybe this uses convnet, if not then it must have come from something i have previously tried or did.

Added some protection to the database so that you cannot basically save any malicious code that could be run.
and added new feature to search from list or filter it basically.

**Comment by 38github** [comment]
I am unable to upload a .nam file which is 401 kB. I get a message stating that my file is too big.

**Comment by jolappi** [comment]
I raised the limit 500kB in database the limit 400kB but that 500kB becomes about 300kB when jsoned.
I made dark mode like the plugin, good or bad?

**Comment by sdatkinson** [comment]
Hi!

Thanks for sharing this! It's cool to see folks getting into it.

Unfortunately, at the moment I'm going to have to put the brakes on my personal involvement with building a model website. The two main reasons are that (1) my free time is already incredibly packed just with the trainer and plugin, but (2) this isn't something where I have the expertise to be able to contribute meaningfully.

**Comment by 38github** [comment]
I can't upload and I recieve "permission denied" when trying to. I have my models self-hosted at the address http://coginthemachine.ddns.net/mnt/nam/

**Comment by jolappi** [comment]
Changed some file size restrictions and tested with couple of those nams, should support more different nams now.
