### ISSUE TITLE
[FEATURE] Add GAIN metadata to .nam model to allow filtering or sorting based on the amount of GAIN a model has

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#127]
As some in the community are busy specing out a browser like Tone.net (ToneX) to allow the community to upload, find and rate NAM models, I would suggest adding a metadata to the .nam file that indicates how much GAIN a model has. That would help when for example, some is looking for AMP X, he can sort all the models of that amp based on it's GAIN.

Kemper does it and it makes browsing and discovering specific tones very easy. 
Additional Metadata like amp name, recording chain could be done inside that upload tool, but GAIN is something the model could provide.

How the kemper displays it:
<img width="1049" alt="Bildschirm­foto 2023-03-14 um 20 13 32" src="https://user-images.githubusercontent.com/783416/225112685-8de51195-41bd-4c65-8969-148855b03280.png">

**Comment by ServusJon** [comment]
Bump :)

**Comment by yovelop** [comment]
Every amp model has it's own level of gain, so it's hard to compare them to get one allaround metric of GAIN.
We can try to measure it by this logic:
Gain increases the volume of the silent(quite) signal, more gain -> louder signal.
in v1_1_1.wav there is local ranges where the same signal goes with different volume levels.
For example if 1 part is quite and 2 part is loud: 
    _volume of 1 part / volume of 2 part = k_input_
In reamped.wav in the same ranges will be:  
    _volume of 1 part / volume of 2 part = k_output_

k_input and k_output <= 1
GAIN = k_output / k_input

**Comment by sdatkinson** [comment]
Implemented in #202 , #203
