### ISSUE TITLE
[BUG] Colab suddenly complaints about 'gpus'

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#128]
```
TypeError                                 Traceback (most recent call last)

[<ipython-input-14-1c067612e5e7>](https://localhost:8080/#) in <module>
----> 1 trainer = pl.Trainer(
      2     callbacks=[
      3         pl.callbacks.model_checkpoint.ModelCheckpoint(
      4             filename="{epoch:04d}_{step}_{ESR:.3e}_{MSE:.3e}",
      5             save_top_k=3,

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/argparse.py](https://localhost:8080/#) in insert_env_defaults(self, *args, **kwargs)
     67 
     68         # all args were already moved to kwargs
---> 69         return fn(self, **kwargs)
     70 
     71     return cast(_T, insert_env_defaults)

TypeError: __init__() got an unexpected keyword argument 'gpus'
```

**Comment by 2-dor** [comment]
> ```
> TypeError                                 Traceback (most recent call last)
> 
> [<ipython-input-14-1c067612e5e7>](https://localhost:8080/#) in <module>
> ----> 1 trainer = pl.Trainer(
>       2     callbacks=[
>       3         pl.callbacks.model_checkpoint.ModelCheckpoint(
>       4             filename="{epoch:04d}_{step}_{ESR:.3e}_{MSE:.3e}",
>       5             save_top_k=3,
> 
> [/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/argparse.py](https://localhost:8080/#) in insert_env_defaults(self, *args, **kwargs)
>      67 
>      68         # all args were already moved to kwargs
> ---> 69         return fn(self, **kwargs)
>      70 
>      71     return cast(_T, insert_env_defaults)
> 
> TypeError: __init__() got an unexpected keyword argument 'gpus'
> ```

Is this from the Google Colab cloud? I was kicked out more times than I can remember midway through training that I decided to give up on Google & worked on getting myself to train locally.

**Comment by 38github** [comment]
Tes, this is in the cloud using the link on the main page. Not the easy training file.

**Comment by sdatkinson** [comment]
PyTorch Lightning updated their API and deprecated this. Seems like the latest version that gets installed now removed that old functionality.

Should be an easy fix. Hang tight.
