### ISSUE TITLE
Different sample rates and bit depths (training)

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#13]
Currently locked it into 48kHz/24-bit just to make sure I don't make mistakes, but this shouldn't need to be the case.

**Comment by sdatkinson** [comment]
Also related--handle this for the plugin.

**Comment by 38github** [comment]
Will there be any issues with mismatching sample rates (project vs model sample rates)? I know other plugins that have problems with that and creates unwanted frequencies, i.e. GuitarML's SmartPedal and Proteus. Chowdhury's implementation of Proteus (LSTM) has a fix for that in an upcoming release.

https://github.com/Chowdhury-DSP/BYOD/issues/250

**Comment by 2-dor** [comment]
Hi Steve. Any chance this one could make it up the priorities list? 
Thank you.
