### ISSUE TITLE
[FEATURE] Pytorch 2.0 is out. Training time improvements?

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#139]
Found out that Pytorch 2.0 has been released supposedly bringing along substantial improvements to training time.

Could it also translate to lower NAM training times?

**Comment by sdatkinson** [comment]
It might. I haven't personally looked into it at all yet, and I've got to admit I probably won't be for quite a while, given competing priorities.  Interested to hear what people find, though and might reconsider if there's a solid case to be made for it.
