### ISSUE TITLE
[FEATURE] - Train generalized models with input parameters - e.g. gain level, channel ...etc.

### ISSUE THREAD

**Issue by cdicle** [sdatkinson/neural-amp-modeler#140]
Current architectures model a single input-output relation with a fixed set of parameters. like gain level, channel, presence ...etc. It is desirable that a single model captures the behavior within a range of parameters, so that user can vary the behavior of the model through parameter adjustment rather than loading multiple models simultaneously. 

There are several neat ways to implement control parameters into architectures, and I have already implemented one toy version. However, this feature begs for a critical improvement in the data pipeline. 
* One-to-many support: The user will submit single input passed through the chain for multiple parameter sets which will produce multiple outputs. Data pipeline should be able to map output files to proper parameter set.

Let me know how you want to collaborate on this feature.

**Comment by sdatkinson** [comment]
Hi. Coming back to this.

I've removed my parametric modeling code from the repo and instead put in place functionality to register custom models and data sets; this should allow you to set things up the way that you'd like e.g. the data pipelining you had in mind.
