### ISSUE TITLE
Idea for NAM 

### ISSUE THREAD

**Issue by Sim16pis** [sdatkinson/neural-amp-modeler#148]
Hello,
basically my general idea was about using the NAM into a computer unit, like the raspberry for exemple, allowing people to run the standalone plugin like a stompbox.
that involves the use of knobs for parameters control, preamps and audio converters, to make it work like a pedal.
would it be ever possible ?

**Comment by Pastew** [comment]
I was thinking about the same, it would be a open source, DIY alternative to Neural DSP Quad Cortex, great idea.
However, I'm wondering if rapsberry is powerfull enough to handle it.

**Comment by Sim16pis** [comment]
> I was thinking about the same, it would be a open source, DIY alternative to Neural DSP Quad Cortex, great idea. However, I'm wondering if rapsberry is powerfull enough to handle it.

These are the Quad cortex specifics..taken as exemple ofc:

SYSTEM FEATURES
Dual enhanced SHARC+ high performance floating-point 
cores
Up to 500 MHz per SHARC+ core
Up to 5 Mb (640 kB) Level 1 (L1) SRAM memory per core 
with parity (optional ability to configure as cache)
32-bit, 40-bit, and 64-bit floating-point support 
32-bit fixed point 
Byte, short-word, word, long-word addressed 
ARM Cortex-A5 core
500 MHz/800 DMIPS with NEON/VFPv4-D16/Jazelle
32 kB L1 instruction cache/32 kB L1 data cache
256 kB Level 2 (L2) cache with parity 
Powerful DMA system
On-chip memory protection
Integrated safety features

Now, im near to no clue on what kind of cpus and ram they used and if those components are expensive, but maybe a 8gb ram raspberry is enough? I dont know :)… the thing about raspberry is that you would need a software to run the NAM

**Comment by GeistRodriguez** [comment]
NDSP uses shark primarily for modeling and effects no?

**Comment by Pastew** [comment]
https://youtu.be/2I_bxxzQs2s

**Comment by sdatkinson** [comment]
There are projects that I'm aware of that are looking into this, like Mike (YT video above). I believe this is the repo, but I haven't really looked at it at all: https://github.com/mikeoliphant/neural-amp-modeler-lv2

Closing this issue since this is the trainer repo and it's out of scope for here.
