### ISSUE TITLE
[BUG] Problem loading .nam files. JSON Exception

### ISSUE THREAD

**Issue by daedspt** [sdatkinson/neural-amp-modeler#149]
Hello people,
This is occurring everytime I try to load any of the .nam files.

**To Reproduce**
1. Load the VST / Standalone
2. Load the .nam file

**Expected behavior**
The following error appears, loading any of the .nam files (with the last version of the plugin):
[json.exception.parse_error.101] parse error at line 8 column 1: syntax error while parsing value - invalid literal; last read:
'<U+000A><U+000A><U+000A><U+000A><U+000A><U+000A><U+000A><'
![image](https://user-images.githubusercontent.com/128589079/226872193-4d78a0d3-be53-49f9-8211-6ea8aa6bcfb3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/128589079/226872218-1e1abdc7-e82a-4b72-aada-58f17c5f48e8.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Reaper DAW
 - VST & Standalone

**Comment by SlayermanGR** [comment]
Most of the cases I've seen for this issue have to do with the path that you've put your models into (most likely it contains a unicode character and NAM can't reach the file).
Try moving your models to a very simple path under you main hard drive (e.g. C:\NAM) until this gets fixed

**Comment by daedspt** [comment]
Yep, tried that aswell, got them on the C;\ root and it gives the same error.
Pretty strange!

**Comment by sdatkinson** [comment]
The error is a parse error--meaning that the contents of the failed appear to be invalid.

Can you try re-downloading the .nam you're trying to use?

If it still doesn't work, can you share with me the file you're trying to use?
