### ISSUE TITLE
[FEATURE] Allow mono input

### ISSUE THREAD

**Issue by ax42** [sdatkinson/neural-amp-modeler#154]
I have a stereo audio device and the guitar just comes in on one channel. I would like to be able to either set both inputs to one channel (2) or set a mono input channel.

<img width="337" alt="Screenshot 2023-03-25 at 14 05 57" src="https://user-images.githubusercontent.com/1254869/227719002-04874a21-96c3-4b1c-888e-d46cc5a3702e.png">

**Comment by ax42** [comment]
Currently, the Input 1 dropdown allows only `1`, the Input 2 dropdown has `1` and `2` listed, but if I set it to `2`, it switches back to `1`.

In my use case, I would like the mono input to be `2`.

**Comment by Bernd-01** [comment]
I also have a Stereo audio input device and for my device (M-Audio M-Track Solo) the guitar amp in is only on the right channel, (channel 2). From what I can tell, there is no way to select the right track only.

**Comment by sdatkinson** [comment]
Hi!  This looks like an Issue for [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin), so I'm going to close it here.

Check out https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/117, which I think captures your Issue. Give it a thumbs-up!
