### ISSUE TITLE
Do not call it "modeler"

### ISSUE THREAD

**Issue by Pinfloid** [sdatkinson/neural-amp-modeler#156]
It is not a modeler (a modeler recreates the actual circuit of the amplifier), it is a capturer/profiler. That is confusing many people at the guitar community

Perhaps change the name to something like Neural-Amp-Capturer?

Thank you

**Comment by sdatkinson** [comment]
NAM creates machine learning models of the tones it's given. [The word "model" is a common term used in deep learning](https://en.wikipedia.org/wiki/Deep_learning) to describe the artifact that's created, so this is following that terminology. Beyond deep learning, [the word "model" has a very broad scope](https://en.wikipedia.org/wiki/Model) that this definitely falls under. 

Neural networks are typically thought of as [_black-box_ models](https://en.wikipedia.org/wiki/Black_box), as opposed to [_grey-box_ models](https://en.wikipedia.org/wiki/Grey_box_model) like you described.

"Profile" and "capture" seem to be invented by the music industry and aren't, in my experience, used anywhere else; so I won't be using them.
