### ISSUE TITLE
[FEATURE] Save and Recall The Users Set GUI Size in Any DAW

### ISSUE THREAD

**Issue by Soniclover** [sdatkinson/neural-amp-modeler#161]
It would be great if the developer can add the feature to allow the users preferred GUI size to be saved as either default in any DAW and for the current saved size of the plugin interface to be recalled when opening DAW projects.

Feature Request:

1.  Save NAMS GUI session size 
2.  Recall NAMS saved GUI size

**Comment by sdatkinson** [comment]
Hi! 

This sounds like an Issue for [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin); would you mind opening it there?

**Comment by Soniclover** [comment]
> Hi!
> 
> This sounds like an Issue for [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin); would you mind opening it there?

Hi Steve, I'm not sure I understand, I did open this as a [ Feature ] in the Neural amp modeller / issues tab section ??
Can you clarify how I need to relabel my request as youve labelled it 'out of scope ' ?
