### ISSUE TITLE
Enhancement Request: Allow for Output.wav to be named uniquely and apply that name to model.nam

### ISSUE THREAD

**Issue by JZ1978** [sdatkinson/neural-amp-modeler#162]
User story:

I am making 20 different versions of an amplifier. I would like to be able to name my Output.wav files uniquely with details about the settings of the amplifier OR just any kind of unique name that helps me remember which one is which. 

When I apply this Output.wav to the training process, I want NAM to accept this file as the Output.wav and apply its name to the outputted model.nam file. 

Example:

Output.wav file #1 is named "5150 BLOCK - b6 m5 t7 d8 p7 crunch - JZ.wav"
Output.wav file #2 is named "5150 BLOCK - b5 m3 t9 d7 p7 lead - JZ.wav"
etc. etc. etc.

Result:
5150 BLOCK - b6 m5 t7 d8 p7 crunch - JZ.nam
5150 BLOCK - b5 m3 t9 d7 p7 lead - JZ.nam
etc. etc. etc.

No need to rename anything.

As I am busy training Output.wav #1, I am also busy reamping output wav #2, 3, 4 and so on. As these reamped output.wav files stack up they get confusing. By allowing us to name the Output.wav with a unique name, this helps the user keep everything organized while they stack up their reamp files waiting for a training session to end. The convenience of having that Output.wav unique name being applied to the model.nam file is obviously superior to keeping notes or keeping sub-folders for an untold amount of models. 

Thanks!

**Comment by JZ1978** [comment]
So apparently, this is already done? And it was done with something called a Pull Request? Im learning here, ok!

Either way, its rad that it works (at least it works on the version Im using). 

1- select v1_1_1.wav with first button
2- multi-select several Output.wav files (btw - you can name those whatever you want now so go ahead and name them after the tone you created)
3- select the destination folder
4- Set your epochs with the Advanced Options button
5- hit "train" button
6- go make tea or go for a walk

**Comment by vossenv** [comment]
> So apparently, this is already done? And it was done with something called a Pull Request? Im learning here, ok!
> 
> Either way, its rad that it works (at least it works on the version Im using).
> 
> 1- select v1_1_1.wav with first button 2- multi-select several Output.wav files (btw - you can name those whatever you want now so go ahead and name them after the tone you created) 3- select the destination folder 4- Set your epochs with the Advanced Options button 5- hit "train" button 6- go make tea or go for a walk

It's accounted for here: https://github.com/sdatkinson/neural-amp-modeler/pull/145

In the GUI mode, but I did not implement that for CLI because it starts via a different process that can accommodate config files and there is more variability in the possible use cases

**Comment by sdatkinson** [comment]
Closing since this is already in (thanks, @vossenv! 🎉 )
