### ISSUE TITLE
validating Audio Unit NeuralAmpModeler by Steven Atkinson:      AU Validation Tool     Version: 1.6.1a1      Copyright 2003-2013, Apple Inc. All Rights Reserved.     Specify -h (-help) for command options  -------------------------------------------------- VALIDATING AUDIO UNIT: 'aufx' - '1YEo' - 'SDAa' -------------------------------------------------- Manufacturer String: Steven Atkinson AudioUnit Name: NeuralAmpModeler Component Version: 0.7.1 (0x701)  * * PASS -------------------------------------------------- TESTING OPEN TIMES: COLD: FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF   validation result: couldn’t be opened[BUG]

### ISSUE THREAD

**Issue by Jayquik** [sdatkinson/neural-amp-modeler#166]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Are you running locally or is this somethig that happens on Colab?
 - Package version (or commit hash?)

**Additional context**

**Comment by sdatkinson** [comment]
Hi!

I can't really tell what's going on here--it looks like you've tried to paste a log in the heading. It looks like it's an Issue related to the plugin, not this repo.
