### ISSUE TITLE
Parametric data input example

### ISSUE THREAD

**Issue by ksanman** [sdatkinson/neural-amp-modeler#167]
I trying to figure out how to train a parametric model, but it's not clear how to format the data config file. Unless I'm missing something there aren't any examples of how to train one of the parametric models. Reading data.py, it seems like there are additional sections needed in the config (slices? params? param_map?), but I'm not sure what the values are supposed to be.

Would it be possible to add a new config(s) to bin\train\inputs\data with a basic example (maybe based off the tube screamer used in the catlstm.config) of how to set up a parametric dataset?

**Comment by sdatkinson** [comment]
I've removed parametric modeling from this package; there's now interfaces to register data sets and models, so if you'd like to do it, you can set it up in the way that makes the most sense for you.
