### ISSUE TITLE
[FEATURE/QUESTION] Is the Amp modeler focused to sound best with guitar amps?

### ISSUE THREAD

**Issue by dmt-hub** [sdatkinson/neural-amp-modeler#169]
Not really a problem, more of a question.
Is the amp modeler focused on guitar amps and the typical frequency response of guitars?
Or can it be used equally well for sampling mastering grade gear like Preamps, Tube/Transistor EQs, Tube Compressors? To be used on full mixes.
Will it perform as well with that task in mind (full spectrum sounds/freq response)? 
or do we need another more specific modeler for that task?

**Comment by sdatkinson** [comment]
NAM may be able to do that, though using the "pre-made" reamp signal and models in the "easy mode" trainers may not do the best job.

My best recommendation would be to just give it a shot and see what you find! If it doesn't work (and there's not an obvious issue with e.g. the receptive field of the model), the first change I might make is to make the training data be more representative of the use case.
