### ISSUE TITLE
[FEATURE]  Ability to continue training for existing .nam

### ISSUE THREAD

**Issue by yovelop** [sdatkinson/neural-amp-modeler#170]
In properties of tstrart trainig procedure add path to .nam file to start trainig from their model weights.
If path = Null - then start normally from begining.

**Comment by sdatkinson** [comment]
This can be done not using a .nam file, but using a Lightning checkpoint.

Provide `"checkpoint_path"` in the [model config](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/models/demonet.json#L40) to use Lightning's [`load_from_checkpoint`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/nam/models/base.py#L133) functionality.
