### ISSUE TITLE
[FEATURE] LUFS model output normalization

### ISSUE THREAD

**Issue by Benjamin-Jon** [sdatkinson/neural-amp-modeler#171]
I would like more consistent level when switching between models.

I humbly suggest that the resulting NAM model to be normalized to a standardized LUFS measurement, for example -10dbLUFS or adjustable with a setting in the training parameters.

RMS level normalization could also be a fine solution, but certain guitar or bass tones having a lot of bass frequency content may unintentionally skew the RMS measurement. A LUFS measurement may provide a more consistent balance across a wider range of tones.

Link to a LUFS measurement algorithm: https://github.com/klangfreund/LUFSMeter

"RMS: the average loudness level of your signal over a given time period using the average power of the signal. LUFS: the average loudness level of your signal over a given time period based on human perception of loudness."

**Comment by sdatkinson** [comment]
I'm going to close this since I'm not planning on doing this (the current non-weighted loudness calculation seems fine).
