### ISSUE TITLE
[FEATURE] Start training from weights of already created nam model of other amp

### ISSUE THREAD

**Issue by yovelop** [sdatkinson/neural-amp-modeler#172]
Every new training process now starts from 0 weights (random seeded weights).
But maybe it'll be better to start training from already trained model of the same architecture.
Process will be:
1) for wght from Pre_Trained_models:
        calc model ESR witth this weights on validation data
    get model with minimum ESR in validation data
2) Start training from this weights

if there will be array Pre_Trained_models with ten or more models of different gain level and amp types (drive, fuzz pedals too) then it can significantly faster achieve good loss value.

**Comment by sdatkinson** [comment]
This can be done using the same solution I described in #170

**Comment by yovelop** [comment]
> This can be done using the same solution I described in #170

this can't be done if you have only .nam, but not checkpoints
