### ISSUE TITLE
No GUI Win 7 Reaper latest version - ( as of 8/4/23). Redistributable latest C ++ 2022

### ISSUE THREAD

**Issue by stevelad33** [sdatkinson/neural-amp-modeler#175]
Win 7 64bit, Reaper latest version ( as of 8/4/23) Redistributable latest C ++ 2022. On board graphics card for a  Dell Precision 7500 32 GB Ram, 12 core 24 hyperthreading ( Not in use) CPU.

No GUI is showing. 

Tried and tested with the exact same install on Win 10 64 bit, laptop I3 intel, Radeon on board graphics card latest Reaper, full GUI available, interactive and functional etc.

**Comment by sdatkinson** [comment]
Hi!

This sounds like an issue for [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin), not this repo (the trainer), so closing as out of scope.

Parenthetically, Windows 8 is the minimum Windows OS officially supported by the plugin.
