### ISSUE TITLE
[BUG] Zero Samples Long

### ISSUE THREAD

**Issue by Simackomen** [sdatkinson/neural-amp-modeler#178]
Hi, how is it going. After the training graph appears, the code claims that my output file is zero samples long. Do you happen to know what is causing the issue? Any help would be greatly appreciated. Thanks!

**Comment by sdatkinson** [comment]
Hi! I need more information to be able to help. If you could please include the full error message that the program gives, what you were running, and what version of the software you're using, that'd help me zone in on a cause.

**Comment by Simackomen** [comment]
Hi! I was able to resolve the issue. As it turned out, when it gave the number of samples, it meant that my input and output audios were not the same length. Thanks for your message anyway! 
By the way, I am a big fan of the work you've done with the NAM. You are a genius!

**Comment by sdatkinson** [comment]
Glad to hear to figured it out!
