### ISSUE TITLE
Installation on MacOSX 10.14.6

### ISSUE THREAD

**Issue by vincentbrun** [sdatkinson/neural-amp-modeler#184]
hello,

is there a version that works with MacOSX 10.14.6

thanks for your help

**Comment by sdatkinson** [comment]
I suspect you're talking about [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin)?

If so, keep an eye on https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/23
