### ISSUE TITLE
[FEATURE] Make modelling process easier

### ISSUE THREAD

**Issue by caleb-shelton** [sdatkinson/neural-amp-modeler#186]
The modelling process/workflow is too manual and difficult to setup for the average user. Having to install extra packages, environments and run commands is already too much for the average user.

Have something similar to other platforms, where you setup your cables, (in this case also then choose your inputs/outputs from your audio interface), and press "Capture".
* No recording > saving > selecting files (this is automated)
* No matplotlib graphs popping up
* Hide away (abstract) configuration to advanced users in a config UI/file.

An alternative could be to make a new repository which imports NAM.

Any ideas/suggestions please let me know.

**Comment by Aelfstone** [comment]
With easy Colab notebook that is provided, it just can't get any easier. You don't need to know all the AI, ML, and DL concepts to successfully get a nice model. The configuration is already banal. Let's not dumb everything down. 

Also, how can you not select files, which are data for training, and make it all "automated"? Where would this automation come from? How would the machine decide which files to use when you have many of them in possibly many locations?

**Comment by sdatkinson** [comment]
For folks looking for the easiest experience, using the Google Colab script is what I recommend (see the README).

The GUI trainer only requires you to 
1. Reamp a file (this is probably the heaviest lift of everything, but I'm not keen to re-invent this wheel).
2. Pick the input & output files from your reamp
3. Pick where the model will be saved
4. And click "train".
