### ISSUE TITLE
[FEATURE] Separate IR loader from main plugin

### ISSUE THREAD

**Issue by wjhemenway** [sdatkinson/neural-amp-modeler#187]
**Thanks for taking the time to write a feature request!** Use the following prompts to help you describe what you're looking for.  The more info you provide, the easier it'll be for me to understand what I can do to make it happen for you without having to come back and ask you questions.

**Is your feature request related to a problem? Please describe.**

Not an issue per say more an enhancement

**Describe the solution you'd like**
Separate the IR loaded from the Main NAM module. I know there are other IR loaders out there
but I believe being able to load the IR anywhere in the signal chain in the DAW is better 
than always right after the amp. This way pedals could be placed between the amp and IR (cab) like
in real life

**Describe alternatives you've considered**
Ther other other IR loaders but I believe a NAM based loader could be made to work better with NAM

**Additional context**

**Comment by nmontua** [comment]
So, uh.. just do not load an IR on the NAM plugin? That is what I do, and it works fine. This request imho is pointless.

**Comment by nmontua** [comment]
I disagree strongly. If you want to use an IR loader in the signal elsewhere in the signal chain, just don't load an IR in the NAM plugin and add your IR loader as a separate FX plugin. Can even be NAM plugin without an amp model. In standalone mode, the IR feature is essential.
