### ISSUE TITLE
Second IR loader

### ISSUE THREAD

**Issue by slavikator** [sdatkinson/neural-amp-modeler#191]
Hi!

Usually, we set up a cab with two mikes. There are a lot of one-mike IRs that can be used. 
It would be really useful to have the possibility of loading two IRs (ex. 57 + 160 or whatever) 

Here is a simple example of what I'm referring to -  https://auroradsp.com/fenrir

**Comment by sdatkinson** [comment]
I'm probably not going to be going very deep on the development of an IR loader.

As a workaround, you can re-bounce the summed IR you want to use, then load that in NAM.
