### ISSUE TITLE
Conda does not recognize "nam" as an environment

### ISSUE THREAD

**Issue by Simackomen** [sdatkinson/neural-amp-modeler#194]
Hi, 
Hope you are going well. For some reason after installing version 10.16 of the neural amp modeler locally on my macOS, conda cannot find the environment "nam". Also, at the end of installation, it does not explain how to activate the amp modeler any other way. Went through the installation process step-by-step two times now, and same result after each time. I have a macOS Ventura 13.0.1. Do you happen to know what might be causing this issue? Any help would be greatly appreciated. 
Thanks

**Comment by Aelfstone** [comment]
I have no idea how different is its use on a Mac from a Win machine, but be sure to execute the commands in the Anaconda Prompt while you're in the same directory as the NAM installation. For instance, on Win when you open the Anaconda Prompt, by default you're in C:\users\User directory. You need to navigate to, let's say, C:\nam and start executing commands from there.

**Comment by sdatkinson** [comment]
I can't really help unless you provide the terminal output as you followed the steps. A straight copy-paste would be extremely helpful.

**Comment by Simackomen** [comment]
![Image 4-29-23 at 4 34 PM](https://user-images.githubusercontent.com/130309626/235323221-2866fe4a-69d9-49e1-81c1-1849e2c74ee3.jpg)

Here is a screenshot of the terminal window. In case if you are not able to open the file, here is exactly what it says:

Last login: Sat Apr 29 16:32:27 on ttys000
base) egormaximenko0Eaors-MBP ~ % conda activate nam
(nam) egormaximenko@Egors-MBP ~ % nam
zsh: command not round: nam
(nam) egormaximenko@Egors-MBP ~%

**Comment by awitez** [comment]
I had to do this on MacOS to install nam:

python setup.py install

and then make sure nam env is activated:

conda activate nam
nam

**Comment by sdatkinson** [comment]
It may be even easier than that:

```
pip install neural-amp-modeler
```
No need to even clone this repo off GitHub first.

I haven't tested it completely yet. Key question is whether it handles MPS correctly for Apple silicon.

Intel should be fine.

**Comment by sdatkinson** [comment]
If folks could test on Apple silicon and report back, that'd be appreciated.

**Comment by awitez** [comment]
M1 Max and M2 here, my env looks like this
[nam.yml.zip](https://github.com/sdatkinson/neural-amp-modeler/files/11516061/nam.yml.zip)

Do you want to know more?

**Comment by sdatkinson** [comment]
@awitez 
> M1 Max and M2 here, my env looks like this [nam.yml.zip](https://github.com/sdatkinson/neural-amp-modeler/files/11516061/nam.yml.zip)
> 
> Do you want to know more?

I don't see either `nam` nor `neural-amp-modeler`. Did it not get installed when you did `pip install neural-amp-modeler` from a fresh environment? (`pip list | grep neural-amp-modeler`?)

And then I'm wondering what the following outputs in python:
```python
import torch
torch.backends.mps.is_available()
```

**Comment by awitez** [comment]
on my M2 MacBookAir I did
`conda create -n nam python=3.10`
`conda activate nam`
`nam`

and everything seems to work fine!

`torch.backends.mps.is_available()`
gives a `true`

installing like this is really easy, on my MacStudio I did a `git pull` and was 'fighting' to solve all the dependencies ;-)

**Comment by awitez** [comment]
this accelerates torch on Apple Silicon:

`conda install pytorch -c pytorch-nightly`

[see here](https://developer.apple.com/metal/pytorch/)

I don't know how much nam relies on numpy, but this speeds it up significantly:

`conda install numpy "libblas=*=*accelerate"`

**Comment by sdatkinson** [comment]
Let's not get ahead of ourselves 😅 Using "fast and dangerous" dependencies is something that I need to be thoroughly convinced about before bringing it into the standard set of dependencies (folks like yourself are more than welcome to hot rod your own install if you know what you're doing).

Sounds like we can at least mark this Issue as resolved, though.

BTW, new how to guide for macOS 🙂 https://youtu.be/8qyJvu9lKO8
