### ISSUE TITLE
[BUG] Focusrrite 2i2 when guitar plug to 2nd input then can't fix input as "#2"

### ISSUE THREAD

**Issue by vacarogit** [sdatkinson/neural-amp-modeler#196]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

 Focusrriteusing  2i2,  when guitar plug to 2nd input then can't fix input as "#2"
on input 1 (L) ...drop down item  fixed to 1 and  2 not available
on input 2 (R) ...drop down item 1 and  2 are both available, BUT it's not possible to select 2 ! obviously a but
so I have to plug guitar to port 1, but I used to put voice microphone to 1...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 7 64bit
 - Are you running locally or is this somethig that happens on Colab?
 - Package version (or commit hash?)

**Additional context**

**Comment by sdatkinson** [comment]
Sounds like this is for the plugin; closing as out-of scope for this repo (the trainer).
