### ISSUE TITLE
[FEATURE] Investigate using Hardtanh for training models

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#197]
Using Hardtanh as the WaveNet activation function seems to work well, and has the potential to be faster than the "fast" tanh. It also has the benefit of being supported directly by pytorch.

**Comment by mikeoliphant** [comment]
I've been investigating this some more, and I haven't yet seen any downside to training ESR using Hardtanh. Some more varied testing would be good, though.

Playback performance is definitely improved, although by how much seems to be compiler-specific. I tested with VS and clang, and saw about a 7% speed increase on the former, and 4% on the latter.

Clang performance was also significantly better than VS - so we may want to be aware of that in general.

I got closer to a 15% increase in speed with gcc on Raspberry Pi - so a lot depends on compiler and platform.

**Comment by sdatkinson** [comment]
Do you notice any difference in the spectrum? Eg aliasing behavior?

**Comment by mikeoliphant** [comment]
> Do you notice any difference in the spectrum? Eg aliasing behavior?

I haven't done any spectral analysis - that isn't something I really have much experience with.

**Comment by sdatkinson** [comment]
Checking back through issues, it looks like this is supported by both this repo as well as the plugin, so I believe that resolves this issue.

If we wanted to e.g. define an architecture that used it (e.g. as part of nano), we could look at that separately.
