### ISSUE TITLE
How do we try out ConvNet instead of WaveNet?

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#199]
I would just like to try it out but I am not sure what changes I have to do in the training settings to achieve this. Thanks in advance!

**Comment by sdatkinson** [comment]
Use [`bin/train/main.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/main.py) with [`convnet.json`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/models/convnet.json). See the README if you're unfamiliar with using the CLI trainer, but that's going to be the best way to use the full power of the trainer :)

**Comment by 38github** [comment]
Thank you. Is it possible to do some changes in the Colab file I use to be able to do ConvNet?
