### ISSUE TITLE
[BUG] : GUI at wrong size

### ISSUE THREAD

**Issue by everythingability** [sdatkinson/neural-amp-modeler#200]
Hi...

my open source DAW of choice is BespokeSynth, but infortunately when using this VST in my projects it looks like this...

<img width="600" alt="image" src="https://user-images.githubusercontent.com/96276/233555657-0264cf37-57b3-4e50-b3b4-45345b613b8f.png">

The view or something surely can be easily fixed?  I'm on.a Mac (M2) Ventura and it does it on an intel64 Monterey too.

Thanks

Tom

p.s the buttons work etc, but not where the image of the gui is... so I have to go fishing to load a model

**Comment by vossenv** [comment]
I think you'll actually want to post this over at https://github.com/sdatkinson/NeuralAmpModelerPlugin (this repo is the trainer)
