### ISSUE TITLE
[FEATURE] The ability to combine two, or more, nam models into one model

### ISSUE THREAD

**Issue by garrrryyyy** [sdatkinson/neural-amp-modeler#201]
**Is your feature request related to a problem? Please describe.**
It would be great if there were a process available in the trainer tool (or even the VST?) that allows a user to combine models, e.g. a user's favorite combination of a TubeScreamer drive pedal model in front of a Marshall amp model. Or consider some users that may want 2 or 3 pedal models stacked in front of an amp model. The ability to sum that into a single nam would be awesome. I do not use the standalone NAM plugin but if it's the same as the VST then I am sure standalone users would benefit from this feature as well.

**Describe the solution you'd like**
I use Ignite Amps Libra as my IR loader and it has a very handy feature with a save button in the VST plugin GUI that brings up a file explorer prompt for you to name and save whatever IR blend you have created as a single IR. A similar feature to that. Example, in the trainer GUI there could be 5 empty fields where the user will select the individual nam models they would like to combine in the order they want the instrument signal path to be in. Ideally there would be a "Normalize" toggle function available for those that prefer it. User defines the destination path for the resulting nam model, then clicks on a "Combine" button to start it. I understand this may not be an instant process like the Libra example where it is doing a much simpler job of summing multiple audio files into one. 

**Describe alternatives you've considered**
The only current alternative I am aware of is running two or more instances of the NAM VST in series with each running a single nam model. 

**Additional context**
Screenshots of Libra if it is unfamiliar
![Libra example](https://user-images.githubusercontent.com/131508128/233765163-aa236576-0231-4c28-a41b-cb639d31a27a.jpg)
![libra2](https://user-images.githubusercontent.com/131508128/233765166-6de0b281-d322-4fe1-a51a-4ae03c2bb03d.jpg)

**Comment by sdatkinson** [comment]
The thing about IRs is to make the sound of a sum of IRs you just sum the WAV files. But for NAM models, you can't do the same thing (sum up the parameters of multiple models and get a model that sounds like the sum of their sounds).

One thing you could do is sum the `output.wav`s and train a model on that? But beyond that, it's not straightforward to accomplish.
