### ISSUE TITLE
GPU PROCESSING

### ISSUE THREAD

**Issue by karlozd** [sdatkinson/neural-amp-modeler#207]
Implement a GPU-based rendering engine, to improve audio latency on underpowered machines.

I am a 3D artist and VFX specialist, I have had the opportunity to use processing through the cuda cores of the graphics cards, this makes the processing times infinitely better than the times when using the CPU cores.

I don't understand why no one has been able to develop systems using the power of GPUs in audio processes, in the same way that it has been used for years in video.

**Comment by sdatkinson** [comment]
Sounds like you meant this for [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin)?

Honestly, this would take quite a bit of work, and battling CUDA isn't my idea of a good time anymore ;) So I'm unlikely to be spending time on this one unless there's something that absolutely cannot run on CPU.
