### ISSUE TITLE
[FEATURE] Making NAM easier to continue training from a previous checkpoint

### ISSUE THREAD

**Issue by fcoberrios** [sdatkinson/neural-amp-modeler#210]
**Is your feature request related to a problem? Please describe.**
It is hard for noobs like me to continue training a model via the checkpoints

**Describe the solution you'd like**
It would be awesome to have a button in the NAM Trainer when pressed you can select the checkpoint file you want to continue so you can continue the training 

**Additional context**
Would be awesome to have something like this 
![Screenshot_1](https://user-images.githubusercontent.com/73447045/234460491-e99e4a3f-cd26-47ed-8f35-9d231bd5acd9.png)

**Comment by sdatkinson** [comment]
Hmm. Thinking out loud:
* Checkbox shouldn't be needed
* Some button to clear the checkpoint
* We'd need to check that the selected checkpoint is compatible with the requested architecture (or perhaps it should override?)
* Might be good to hide it away from the main screen. I want to keep it as minimal as possible as a first impression. Under advanced options perhaps?

**Comment by 38github** [comment]
I would really like this. Training equipment with several captures of different settings would hopefully save A LOT of time.

**Comment by sdatkinson** [comment]
Let me take a shot at this.
