### ISSUE TITLE
Weight pruning

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#22]
Try weight pruning: Train a bigger net, then prune back to the desired size. Can this get better fits?

**Comment by GuitarML** [comment]
@sdatkinson You might have already seen this paper from Nov 2022, but I'll post here for reference just in case:
https://ieeexplore.ieee.org/document/9954902/references#references

Looks like they were able to get significant speed improvements by pruning LSTM models.

**Comment by sdatkinson** [comment]
Not a priority / closing this Issue to tidy up :)
