### ISSUE TITLE
[FEATURE] Implementing Antiderivative Anti-Aliasing possible?

### ISSUE THREAD

**Issue by dmt-hub** [sdatkinson/neural-amp-modeler#221]
**Is your feature request related to a problem? Please describe.**
Supressing aliasing without oversampling to have a signal more true to the analog source (saturation/distortion)

**Describe the solution you'd like**
Implementing Antiderivative Anti-Aliasing.
from: https://jatinchowdhury18.medium.com/practical-considerations-for-antiderivative-anti-aliasing-d5847167f510
source code: https://github.com/jatinchowdhury18/ADAA

**Additional context**
This new method to supress aliasing seems really good.

**Comment by sdatkinson** [comment]
Interesting. Let me have a think about this.

**Comment by sdatkinson** [comment]
After having looked at this, it looks like a fair bit of work and not something that I really see myself having time for right now, so I'm going to close this.
