### ISSUE TITLE
I cant hear the tone from the standalone app. Pls help me :([BUG]

### ISSUE THREAD

**Issue by bizzzar0** [sdatkinson/neural-amp-modeler#227]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Are you running locally or is this somethig that happens on Colab?
 - Package version (or commit hash?)

**Additional context**

**Comment by sdatkinson** [comment]
You want [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin)
