### ISSUE TITLE
[BUG]Conda installer errors out installing onnxruntime on Ubuntu 22.04

### ISSUE THREAD

**Issue by patrickkpowell** [sdatkinson/neural-amp-modeler#228]
Running conda installer produces the following on Ubuntu 22.04 Virtual Machine with PCI NVDIA device exposed to the VM and drivers installed. 

Command
conda env create -f environment_gpu.yml

Output
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

\ By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
  https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/ppowell/anaconda3/envs/nam/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/user/neural-amp-modeler/condaenv.pto42vdh.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining file:///home/ppowell/neural-amp-modeler (from -r /home/user/neural-amp-modeler/condaenv.pto42vdh.requirements.txt (line 8))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting auraloss==0.3.0 (from -r /home/user/neural-amp-modeler/condaenv.pto42vdh.requirements.txt (line 1))
  Using cached auraloss-0.3.0-py3-none-any.whl (15 kB)
Collecting onnx (from -r /home/user/neural-amp-modeler/condaenv.pto42vdh.requirements.txt (line 2))
  Using cached onnx-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by sdatkinson** [comment]
What happens if you run `pip install onnxruntime` on a fresh environment?

**Comment by patrickkpowell** [comment]
It installs in the base OS.  Do you mean another conda environment?  I'm not really familiar with conda, is it just making a python venv?

**Comment by jtemple967** [comment]
Can confirm I got the same error on Ubuntu 22.04 but not on a virtual machine. I can run pip install onnxruntime just fine from the command line.

**Comment by renebohne** [comment]
I got the same error on Ubuntu 23.04 which installed python3.11 in the conda env. According to this issue, python3.11 is not yet supported by onnxruntime: https://github.com/microsoft/onnxruntime/issues/14880

Maybe the default python version for anaconda envs on Ubuntu 22.04 has a similar problem?

My fix is to add this line in the environment_gpu.yml file (under dependencies):
- python=3.10.10

**Comment by sdatkinson** [comment]
Nice. I'll get a fix in then

**Comment by jtemple967** [comment]
Can also confirm renebohne's fix also fixes the problem on Ubuntu 22.04.  However I had to put the change in environment_cpu.yml as I don't have the GPU to use environment_gpu.yml.
