### ISSUE TITLE
[FEATURE] Giving the EQ section different sets of parameters with a menu to select the different EQ types

### ISSUE THREAD

**Issue by JZ1978** [sdatkinson/neural-amp-modeler#230]
People want knob modeling which would be impossible so how about an easier solution: 

Similar to Kempers idea of "liquid modeling" this tool could be used to calculate different ways of incorporating the EQ section of NAM, giving it parameters that are similar to the most common types of EQ found on the majority of amplifiers (Fender style, Marshall style, Vox style). This tool shows how these curves are calculated so it may help with implementation:
https://www.duncanamps.com/tsc/

This would give the user a more realistic post EQ section. They may also be able to use the "wrong" EQ section with a NAM model if that EQ type suits their needs. These EQ types would not be hard-tied to a NAM model but rather a selectable menu (ideally). 

Hard mode:
The way Kemper seems to be implementing this is a bit more complex, where the user must know the knob positions of the model and then assign a starting position to those knobs on the "liquid model" EQ section. This might take a bit of extra effort but I can see people asking for this. 

EG:: NAM model of a Marshall JCM800 with Bass/Mid/Treble at 7/3/8 (out of 10). Knowing this, the EQ would position itself at those positions but would actually be "flat" in those positions so the model sounds the same as if the EQ was bypassed. When the knobs are moved, they then cut and boost as expected, with a similar reaction as what is shown by the Tone Stack Calculator mentioned above.

**Comment by sdatkinson** [comment]
Sounds like this is meant for the plugin? So closing here.

But I'm not against the idea of the EQ effected by the knobs being something other than the currently-implemented biquads :)

**Comment by JZ1978** [comment]
Ah! If I should have put this on a different page, I apologize.
