### ISSUE TITLE
Struggling to model

### ISSUE THREAD

**Issue by CalebBassham** [sdatkinson/neural-amp-modeler#235]
**Describe the bug**
I'm trying to play around with this awesome project. I have a recording of an amp using the sample v1_1_1.wav file. When I try to start training I get an error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/nam/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/caleb/repos/neural-amp-modeler/nam/train/gui.py", line 300, in _train
    trained_model = core.train(
                    ^^^^^^^^^^^
  File "/Users/caleb/repos/neural-amp-modeler/nam/train/core.py", line 556, in train
    if not _check(input_path, output_path, input_version):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/caleb/repos/neural-amp-modeler/nam/train/core.py", line 308, in _check
    if input_version.major == 1:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'major'
```

Side note: this is after I have set delay to 0 because it wasn't able to find it automatically.

![image](https://user-images.githubusercontent.com/22458879/236604907-4c11c612-27fe-4b2e-bb28-ae46bf899775.png)

![image](https://user-images.githubusercontent.com/22458879/236605156-e3a48756-f2a8-442e-b96e-442bca0ba1dd.png)

**To Reproduce**
Start training.

**Expected behavior**
Training starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/22458879/236603946-364323d2-b772-4ebe-87f4-b6ffb25d6f2a.png)

Waveform of the start of my recording. I assume the calibration are the first 2 blips or maybe the second 2 or both.

![image](https://user-images.githubusercontent.com/22458879/236604516-4744f4f7-6d3a-4f25-934e-bcd48b7f6ae4.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/22458879/236603595-b0376a42-37e9-4b2e-a8bd-c2bc92026370.png)

NAM version 00cf5829

**Additional context**

**Comment by CalebBassham** [comment]
Update: got it working with my own DI as input! Remains to be seen if my training data producing something usable.

**Comment by sdatkinson** [comment]
Closing since it sounds like you're good?
