### ISSUE TITLE
Version 0.7.3 - UI changes and future improvements

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#240]
I feel like the new UI is a good step in the right direction but the skeuomorphic elements (many gradients and almost 3d look) and little contrast makes it harder to use than it used to be.

Things I would change:

- Increase contrast on the knobs (maybe getting rid of the outer glow and gradients on the knobs). They look shiney but makes it harder to use
- Add arrow buttons on the .nam file field that are next to each other (left right directly next to each other to allow fast switching)
- Get rid of the dark lines around the UI
- Add "Gate" label to toggle
- Make the logo smaller

I can also help to make a design draft. But I would actually like to think about the future, including a bigger emphasize on file browser / searching and selecting from tonehunt, favorites,...

What do you think @sdatkinson ?

**Comment by sdatkinson** [comment]
Can I get this over on [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin)?
