### ISSUE TITLE
[BUG] CondaEnvException: Pip failed

### ISSUE THREAD

**Issue by mattgoings** [sdatkinson/neural-amp-modeler#241]
Hi, I'm getting this error in Anaconda when trying to set up my PC for local training.
This is after doing a fresh install of Anaconda & Git.

```
(base) C:\Users\Matt>cd C:\Users\Matt\NAM\neural-amp-modeler

(base) C:\Users\Matt\NAM\neural-amp-modeler>
(base) C:\Users\Matt\NAM\neural-amp-modeler>conda env update -f environment_gpu.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\Users\Matt\anaconda3\envs\nam\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\Users\Matt\NAM\neural-amp-modeler\condaenv.tigoz9zg.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining file:///C:/Users/Matt/NAM/neural-amp-modeler (from -r C:\Users\Matt\NAM\neural-amp-modeler\condaenv.tigoz9zg.requirements.txt (line 8))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting auraloss==0.3.0 (from -r C:\Users\Matt\NAM\neural-amp-modeler\condaenv.tigoz9zg.requirements.txt (line 1))
  Using cached auraloss-0.3.0-py3-none-any.whl (15 kB)
Collecting onnx (from -r C:\Users\Matt\NAM\neural-amp-modeler\condaenv.tigoz9zg.requirements.txt (line 2))
  Using cached onnx-1.14.0-cp311-cp311-win_amd64.whl (13.3 MB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

failed

CondaEnvException: Pip failed
```

Running Windows 10 with a GTX 1080ti. On my other weaker Windows 10 desktop with a GTX 960 I don't have this problem, for whatever reason.

When I try to start GUI training after this error, this is what I get:

```
(base) C:\Users\Matt\NAM\neural-amp-modeler>conda activate nam

(nam) C:\Users\Matt\NAM\neural-amp-modeler>nam
'nam' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by 2-dor** [comment]
If you navigate to the neural-amp-modeler folder & do a " pip install -e ." does it work after?

**Comment by mattgoings** [comment]
> If you navigate to the neural-amp-modeler folder & do a " pip install -e ." does it work after?

This is what I get when I do that:

```
(base) C:\Users\Matt\NAM\neural-amp-modeler>pip install -e

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
```

Unfortunately I still get the same error when trying to do conda env update -f environment_gpu.yml

**Comment by 2-dor** [comment]
> > If you navigate to the neural-amp-modeler folder & do a " pip install -e ." does it work after?
> 
> This is what I get when I do that:
> 
> ```
> (base) C:\Users\Matt\NAM\neural-amp-modeler>pip install -e
> 
> Usage:
>   pip install [options] <requirement specifier> [package-index-options] ...
>   pip install [options] -r <requirements file> [package-index-options] ...
>   pip install [options] [-e] <vcs project url> ...
>   pip install [options] [-e] <local project path> ...
>   pip install [options] <archive url/path> ...
> 
> -e option requires 1 argument
> ```
> 
> Unfortunately I still get the same error when trying to do conda env update -f environment_gpu.yml

Make sure you include the dot . in the command

**Comment by mattgoings** [comment]
> > > If you navigate to the neural-amp-modeler folder & do a " pip install -e ." does it work after?
> > 
> > 
> > This is what I get when I do that:
> > ```
> > (base) C:\Users\Matt\NAM\neural-amp-modeler>pip install -e
> > 
> > Usage:
> >   pip install [options] <requirement specifier> [package-index-options] ...
> >   pip install [options] -r <requirements file> [package-index-options] ...
> >   pip install [options] [-e] <vcs project url> ...
> >   pip install [options] [-e] <local project path> ...
> >   pip install [options] <archive url/path> ...
> > 
> > -e option requires 1 argument
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately I still get the same error when trying to do conda env update -f environment_gpu.yml
> 
> Make sure you include the dot . in the command

Ah, sorry, definitely a difference there. Sadly I'm still getting the same error though.

**Comment by mattgoings** [comment]
Ok so despite it giving me that error again, I restarted the computer, tried conda activate nam followed by nam, and now the GUI trainer is working! The previous restart attempts didn't help, but this one after pip install -e . must've done the trick. Thanks!

**Comment by sdatkinson** [comment]
> Ok so despite it giving me that error again, I restarted the computer, tried conda activate nam followed by nam, and now the GUI trainer is working! The previous restart attempts didn't help, but this one after pip install -e . must've done the trick. Thanks!

If you installed the drivers for your GPU on Windows as part of getting set up with this, you have to restart before the changes take effect.

Everything else should work without a restart, though.
