### ISSUE TITLE
Error attempting to install NAM Locally[BUG]

### ISSUE THREAD

**Issue by Rickplaysbass** [sdatkinson/neural-amp-modeler#246]
Upon attempting to install NAM locally I have a fresh install of Anaconda and am on Windows 10 Home
Version 22H2
OS Build 19045.2965

When I get to this script to install NAM, this is the failed result I receive

 (base) C:\Users\Rick\Desktop\NAM\neural-amp-modeler>conda env update -f environment_gpu.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
pywin32-304          | 9.5 MB    | ############################################################################ | 100%
typing_extensions-4. | 31 KB     | ############################################################################ | 100%
openjpeg-2.5.0       | 232 KB    | ############################################################################ | 100%
sniffio-1.3.0        | 14 KB     | ############################################################################ | 100%
widgetsnbextension-4 | 828 KB    | ############################################################################ | 100%
libtiff-4.5.0        | 1.0 MB    | ############################################################################ | 100%
cuda-cudart-11.7.99  | 1.4 MB    | ############################################################################ | 100%
cuda-cupti-11.7.101  | 10.2 MB   | ############################################################################ | 100%
libuv-1.44.2         | 362 KB    | ############################################################################ | 100%
libcublas-11.10.3.66 | 24 KB     | ############################################################################ | 100%
winpty-0.4.3         | 1.1 MB    | ############################################################################ | 100%
backports-1.0        | 6 KB      | ############################################################################ | 100%
certifi-2023.5.7     | 149 KB    | ############################################################################ | 100%
pkgutil-resolve-name | 9 KB      | ############################################################################ | 100%
pyzmq-25.0.2         | 467 KB    | ############################################################################ | 100%
rfc3339-validator-0. | 8 KB      | ############################################################################ | 100%
tinycss2-1.2.1       | 23 KB     | ############################################################################ | 100%

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['C:\\Users\\Rick\\anaconda33\\envs\\nam\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\Rick\\Desktop\\NAM\\neural-amp-modeler\\condaenv.f4fb1esl.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining file:///C:/Users/Rick/Desktop/NAM/neural-amp-modeler (from -r C:\Users\Rick\Desktop\NAM\neural-amp-modeler\condaenv.f4fb1esl.requirements.txt (line 8))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting auraloss==0.3.0 (from -r C:\Users\Rick\Desktop\NAM\neural-amp-modeler\condaenv.f4fb1esl.requirements.txt (line 1))
  Using cached auraloss-0.3.0-py3-none-any.whl (15 kB)
Collecting onnx (from -r C:\Users\Rick\Desktop\NAM\neural-amp-modeler\condaenv.f4fb1esl.requirements.txt (line 2))
  Using cached onnx-1.14.0-cp311-cp311-win_amd64.whl (13.3 MB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

failed

CondaEnvException: Pip failed

**Comment by sdatkinson** [comment]
What version of Python are you using? You can find out with `python --version` in the Aanconda prompt.

Can you confirm that `environment_gpu.yml` contains [`python<3.11`](https://github.com/sdatkinson/neural-amp-modeler/blob/29d1fb038f892a227e27b461553ea0ce350d3eeb/environment_gpu.yml#L11)?  If it doesn't, then you need to update (I think I merged in this fix very recently...)

**Comment by Rickplaysbass** [comment]
Python 3.10.09

I added that line to the GPU.yml file under dependencies and it installed.
