### ISSUE TITLE
[FEATURE] assert input preceding a train/validation interval is silent

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#252]
Make a FR of #247.

The root cause was that the training signal went right up to the start of the validation, so the beginning of the output in the validation audio was from the last of the input in the training data (and therefore impossible to predict).

To resolve this Issue, implement a check that the preceding half second of input (or as much as exists) is silent. Apply it whenever a data set is being created (training as well as validation).

**Comment by karan1508** [comment]
Can I take this up?

**Comment by sdatkinson** [comment]
Hey @karan1508!

Unfortunately (for you) I was working on this for fun during vacation and didn't have a chance to see your offer before it was almost done.

I'll be working on flagging more issues as "good first issues" soon and I hope we can find something for you!

Again, sorry you weren't able to get in on this one but I wanted to touch back since I very much appreciate that you stopped by in the Issue to offer 😄
