### ISSUE TITLE
Logic NAM Issue (an audio unit plugin reported a problem)

### ISSUE THREAD

**Issue by incertracing** [sdatkinson/neural-amp-modeler#259]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
When i launch NAM in Logic Pro and i load an amp, within 10-15 secs after i start setting levels and the gate etc a dialogue box comes up saying "an audio unit plugin reported a problem which might cause the system to become unstable. Please quit and restart Logic Pro." If i hit cancel it reloads the session and it will happen exactly same way again after 10-15 secs. If i quit logic and start over, it still does the same thing. Its actually hampering my use of the plugin to the point that i will not use it til an update comes out and has a fix.

**To Reproduce**
1. Go to Audio Track, Audio FX, Audio Units, Steven Atkinson, NeuraAmp Modeler.
2. Click on Add Model. Add amp Model. Start setting levels and Gate.
3. See error "an audio unit plugin reported a problem which might cause the system to become unstable. Please quit and restart Logic Pro."

 - Apple MacBook Pro 16in, 32GB Ram, 1TB SSD, Apple Silicon M1 MAX
 - Mac OS Ventura 13.4
 - Running NAM Ver: 0.7. 3 as a plugin in Logic Pro X 10.7.8
 - Focusrite Scarlet 18i20 3rd Gen

![349639686_700279641858942_3336234370478331994_n](https://github.com/sdatkinson/neural-amp-modeler/assets/135188052/312f2fd6-37c9-4747-a915-002261176fc6)

**Comment by sdatkinson** [comment]
Please report this over at https://github.com/sdatkinson/NeuralAmpModelerPlugin

Thanks!
