### ISSUE TITLE
[BUG] Switching from DirectSound to ASIO causes abend

### ISSUE THREAD

**Issue by cincypiper** [sdatkinson/neural-amp-modeler#263]
HW Info:

Computer:      LENOVO Legion 5 Pro 16IAH7H
CPU:           Intel Core i7-12700H (Alder Lake-H 682, L0)
               2700 MHz (27.00x100.0) @ 4389 MHz (44.00x99.8)
Motherboard:   LENOVO LNVNB161216
BIOS:          J2CN49WW, 11/25/2022
Chipset:       Intel Alder Lake-P PCH
Memory:        32768 MBytes @ 2394 MHz, 40-39-39-76
               - 16384 MB PC38400 DDR5 SDRAM - Samsung M425R2GA3BB0-CQKOL
               - 16384 MB PC38400 DDR5 SDRAM - Samsung M425R2GA3BB0-CQKOL
Graphics:      Intel Iris Xe Graphics (Alder Lake-P 682 GT2) - Integrated Graphics Controller [Lenovo]
               Intel Iris Xe Graphics, 1024 MB DDR4 
Graphics:      NVIDIA GeForce RTX 3070 Ti Laptop (GA104M) [Lenovo]
               NVIDIA GeForce RTX 3070 Ti Laptop, 8192 MB GDDR6 SDRAM
Drive:         SAMSUNG MZVL21T0HCLR-00BL2, 1000.2 GB, NVMe
Sound:         Intel Alder Lake-P PCH - cAVS (Audio, Voice, Speech)
Sound:         NVIDIA GA104 - High Definition Audio Controller
Network:       Intel Wi-Fi 6E AX211 160MHz
Network:       RealTek Semiconductor RTL8168/8111 PCI-E Gigabit Ethernet NIC
OS:            Microsoft Windows 11 Home (x64) Build 22621.1702 (22H2)

USB I/O device:  Native Instruments Komplete Audio 6, firmware up to date.

Abend ocurrs by selecting 'ASIO' as the sound driver on the preferences dialog.

Abend also occur when 'Apply' or 'Ok' is pressed when the Input source or Output Sources are set to use my Native Instruments inputs.

**Comment by cincypiper** [comment]
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/2415246/fd9a09e2-0e28-46b0-b0e3-7d0ed538bae6)

Selection of ASIO causes Abend.

**Comment by RustoMCSpit** [comment]
There should also be more Linux drivers, I know this isn't super related but felt I needed to say it
