### ISSUE TITLE
Will the "advanced" Colab file be updated to 0.6?

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#267]
I have lots of old files not using v2_0_0.wav or the official input filkes and I would like to specify my own x_train and y_train. I don't know how to retrain any of the models without it.

**Comment by sdatkinson** [comment]
Ah, I had said at the top that I'd remove it, huh?

Just had a look through it and the good news is that if you want to keep on using it, I'm pretty sure you can--just remove the `<=0.5.3` bit and everything else seems like it'll still work.

And you can always keep a personal copy of that Colab notebook (or grab it from a previous version here when you need it, or keep a copy in your own repo)--all I'm saying is that I'm not going to be prioritizing keeping it working over here.
