### ISSUE TITLE
[FEATURE] Add final ESR to model metadata

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#270]
Even though the ESR isn't an absolute value (since it depends on the validation data used), it would be useful to have the final model ESR stored in the metadata.

On a related note, if the model was trained on a known (ie: v1_1_1.wav) input signal, having that information stored in the metadata could also be useful.

**Comment by sdatkinson** [comment]
Seems doable.

Is there a use case for this beyond curiosity?

**Comment by mikeoliphant** [comment]
> Is there a use case for this beyond curiosity?

Just for info - like other metadata. More useful for "trainers" than "users", probably. I often re-train on the same capture file under different conditions, and it is useful to know what kind of ESR was previously attained.

**Comment by vossenv** [comment]
+1 - I was thinking about adding this myself locally at the same time I append it to the filenames after the fact.  It's helpful for my own tracking if nothing else, but I think also a good reference data point.  While I believe in "sounds good is good", I think there's value in this since the test data is effectively standardized

**Comment by 2-dor** [comment]
+1 here too. Would love to have this cooked into the model.

**Comment by 38github** [comment]
+1

**Comment by mikeoliphant** [comment]
Unsurprisingly (since I opened the issue), I disagree and think it would be useful to have this information (as well as any other potentially informative information about the training process/results) embedded in the resulting model - which is all the end user will have access to.

As you say, it could easily be done in a fork, but my thoughts are are along the lines of "this would generally be useful for NAM users" rather than a specific need of mine.
