### ISSUE TITLE
[FEATURE] Publish documentation

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#277]
Sphinx/readthedocs

**Comment by sdatkinson** [comment]
🎉

**Comment by pacharanero** [comment]
Hi @sdatkinson I was super excited to find this amazing project over the weekend, and wanted to give some support somehow. I'm a 30-year+ guitarist and distortion nerd, and I've used a huge range of modelers over the years, but was very impressed by the commercial 'Nano Cortex' amp capture technology (which I currently use) and then found this even more exciting open source equivalent (which I now want to switch to!).

I would love to help out with documentation of all 3 repos, if this was required. Doing so would help me learn how each of the repos works, and I would be able to test them running in a Linux environment (I am on an Ubuntoid Linux and experienced Linux user and developer).

Possibly it would be worth trying to unify the 3 into a single canonical site eg docs.neuralampmodeler.com covering everything related to NAM, for the various different 'audiences' including industry implementers, amateur hobbyists, etc. Everything from a getting started through to a curated and updated list of all hardware supporting NAM now.

My preference would be to use [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) which is a beautiful theme for MkDocs, and which I have a lot of experience with [[1](https://growth.rcpch.ac.uk/)] [[2](https://gitehr.org/)] [[3](https://dcsalliance.org/)] [[4](https://playbook.rcpch.tech/)] and consider it to be one of the best documentation frameworks out there. It's used by a lot of [new and interesting Python projects](https://github.com/squidfunk/mkdocs-material#trusted-by-).

I also do a lot of [Discourse](discourse.org) forum building, so if the community started to reach a size at which a forum made sense I could help with doing that.

**Comment by sdatkinson** [comment]
@pacharanero  Thanks for getting in touch! 

Part of what you described is what I'm intend for neuralampmodeler.com accomplish :)

However, a similar readthedocs for at least [NeuralAmpModelerCore](https://github.com/sdatkinson/NeuralAmpModelerCore) seems appropriate. For [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin), there's documentation that's distributed in the installer, but I suppose that some "for devs" documentation would also be nice. (One thing that deserves to be in it is certainly how to do calibration, as it seems that a lot of people don't understand it intuitively!)

As a first step, if you wanted to put an Issue down in the core for Sphinx/readthedocs, I'd be happy to assign it to you. Then feel free to start with a snippet of it (especially if there's some systematic change in how the code is documented--I assume there will be) and I can review that before/any suggestions/comments before proceeding with the rest.

**Comment by pacharanero** [comment]
Hi @sdatkinson - sorry for slow reply, got quite busy with work stuff.

* I would aim not to have to change the way the code is documented, rather we would try to pull static docs from the codebase into markdown files that Material for MkDocs could use. This might be achieved with a GitHub Action to poll each repo and get the relevant docs from each one.

* The idea would then be that all the documentation would be in a single place, with navigation tabs for each kind of user (eg. Musicians just wanting to use NAM, Developers wanting to build with NAM, etc)

I'll create the Issue in Core
