### ISSUE TITLE
[FEATURE] getting this error in NAM Failed checks! (To disable this check, run AT YOUR OWN RISK with `ignore_checks=True`.) In no coder is this something i need to change somewhere? thanks

### ISSUE THREAD

**Issue by jacko213** [sdatkinson/neural-amp-modeler#278]
**Thanks for taking the time to write a feature request!** Use the following prompts to help you describe what you're looking for.  The more info you provide, the easier it'll be for me to understand what I can do to make it happen for you without having to come back and ask you questions.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sdatkinson** [comment]
So, what you _should_ do first is check out what's going wrong--you may have bad data, and, as they say, "Garbage in, garbage out"! 😉 

But, if you think that the checks don't know what they're talking about and you want to try anyways,

Then take this...

<img width="543" alt="image" src="https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/76bf7e26-c75e-4db0-903d-73262a74bda9">

and make it like this:

<img width="535" alt="image" src="https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/01d2ae39-f1e2-450e-a954-beab21935fdf">

Good luck!
