### ISSUE TITLE
[FEATURE] controlling synth with guitar 

### ISSUE THREAD

**Issue by ositaunus** [sdatkinson/neural-amp-modeler#285]
is there anything in the domain of machine learning for controlling a synth with a guitar, making a guitar sound like a synth, or turning the guitar signal into midi in a live setting?

**Comment by sdatkinson** [comment]
I haven't tried, though I'm sure there is--I'd think one could repurpose approaches developed for detection in computer vision and be pretty successful 🙂

Closing since I won't be working on anything along those lines in this repo.
