### ISSUE TITLE
[BUG] Standalone version isn't reading the correct inputs. 

### ISSUE THREAD

**Issue by tabqwerty** [sdatkinson/neural-amp-modeler#287]
https://github.com/sdatkinson/neural-amp-modeler/assets/40632509/0dead23d-02c4-48f5-9b3b-eb65f36fd257

**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

Sorry about my frustration in the video, but standalone isn't working on Windows 10 64-bit (at least not for Scarlett Solo 3rd Gen).

**To Reproduce**

**Expected behavior**

For the numbers to not jump around as they do and that they'd read the input.

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Are you running locally or is this somethig that happens on Colab?
 - Package version (or commit hash?)

**Additional context**

**Comment by sdatkinson** [comment]
This is being tracked over on the plugin repo: https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/157

So I'm going to close this as a duplicate.
