### ISSUE TITLE
[FEATURE] IR Normalization on NAM plugin IR loader

### ISSUE THREAD

**Issue by JZ1978** [sdatkinson/neural-amp-modeler#288]
The IR loader on NAM does not normalize the output level of IRs. This causes some IRs to be very loud and others to be very quiet. 

Demo video (unlisted):
https://youtu.be/xqpA6RBFz1U

Link to IRs used in video:
https://drive.google.com/file/d/14k9mRz8k2wqyYeyQPGwVkb1BNKTinwev/view?usp=drive_link

It would be great if the IR loader could be enhanced to normalize the IR that is loaded into it. 
These are example IRs of the exact same tone, exported with different volumes. 

If you load these IRs into any popular external IR loader (NadIR, MConvolutionEZ, etc) they will all have the same output volume. If you load them into NAM, they have different output volumes. 

**Additional context**
This would prove very useful for a project I am working on that would allow me to very easily integrate JZIR into NAM where I would have 2 IRs in series. The first IR which would load into NAM would be the "eq correction" IR which would standardize the EQ output of every NAM profile (this IR is very quiet right now which is primarily why Im asking for this enhancement) then the 2nd IR would be loaded in an external IR loader and that would have the band/song/album tone. You can download my example workflow for possible NAM integration for JZIR here:
https://drive.google.com/file/d/12uLZNhOp3l4m8ACo_3FPx94SJWYKNGij/view?usp=drive_link

**Comment by sdatkinson** [comment]
> If you load these IRs into any popular external IR loader (NadIR, MConvolutionEZ, etc) they will all have the same output volume.

I wasn't aware of this. Do you happen to know how the normalization is done? I can think of a few ways (e.g. RMS of the IR), but if there's something that is known to work well and make people happy I might as well do it that way.

> ... add this as a feature request to the plugin side of things rather than here -
> https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues

Ah yep, what Dom said 😉  I'll probably lose it here by tomorrow 😅

**Comment by JZ1978** [comment]
Fixed. My bad!
https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/313
