### ISSUE TITLE
[BUG] ImportError calling 'nam'

### ISSUE THREAD

**Issue by joeljaffesd** [sdatkinson/neural-amp-modeler#293]
erBase
ImportError: cannot import name 'AutoModelForMaskedLM' from 'transformers' (/Users/joeljaffe/anaconda3/lib/python3.11/site-packages/transformers/__init__.py)

^Error thrown when calling nam after importing libraries. How can this be remedied?

**Comment by sdatkinson** [comment]
This doesn't provide enough context. `transformers` isn't even a dependency of this repo.

Please post enough information to be able to replicate the issue--how you created your environment, what you ran, and the complete output.

**Comment by joeljaffesd** [comment]
Did some troubleshooting with Chat and figured out this issue was caused by outdated Python script on my machine. Apologies for taking your time. Really love the software, theorized it in school and was ecstatic to discover it had not only been realized but also released open-source and with a great community framework. Cheers!
