### ISSUE TITLE
[BUG] Large Negative delays in time cause training to fail

### ISSUE THREAD

**Issue by loki42** [sdatkinson/neural-amp-modeler#304]
With file with large ish negative delay:

Delay wasn't provided; attempting to calibrate automatically...
Delays:
 -1000
 -1000
After aplying safety factor, final delay is -1004
-Checks passed

gives 0.9979 error ratio.

after adding silence,
sox test.wav -twavpcm -b24 out_trim.wav pad 1500s 0

and trimming to correct length
trim 0s 8592000s

Delay wasn't provided; attempting to calibrate automatically...
Delays:
 123
 123
After aplying safety factor, final delay is 119

Error-signal ratio = 0.01162

Is 1000 the max delay either way? Should the code report that as a warning?

Running today's github main branch pull, using the python code directly (no UI).

**Comment by sdatkinson** [comment]
Regarding the initial issue, there's apparently some noise in your reamp that's causing it to immediately trigger the detection threshold. Hard to say without being able to see the audio in question.

> Is 1000 the max delay either way?

[It's the max in the direction that looks for if the latency is _over_-compensated; under- or non-compensated, it looks 10,000 samples.](https://github.com/sdatkinson/neural-amp-modeler/blob/06547c8579cbec9f0eb4f8ca732083e91b672e4e/nam/train/core.py#L217C6-L217C6)

> Should the code report that as a warning?

Great idea; I'll tackle this right now 🙂

**Comment by sdatkinson** [comment]
Implemented the warning; is there anything else you suggest before this Issue can be closed?

**Comment by loki42** [comment]
No,  that's good.
