### ISSUE TITLE
[BUG] can't train with v2_0_0.wav

### ISSUE THREAD

**Issue by warpkwd** [sdatkinson/neural-amp-modeler#308]
**Describe the bug**
can't train with v2_0_0.wav

**To Reproduce**
1. set files 'v2_0_0.wav' and 'output.wav' by uploading 
2. Click on 'train'
3.  See error
```
/usr/local/lib/python3.10/dist-packages/nam/train/colab.py in _check_for_files()
     47             break
     48     else:
---> 49         raise FileNotFoundError(
     50             f"Didn't find NAM's input audio file. Please upload {_LATEST_VERSION[1]}"
     51         )

FileNotFoundError: Didn't find NAM's input audio file. Please upload v2_0_0.wav
```
**screen shot**

![num_err](https://github.com/sdatkinson/neural-amp-modeler/assets/7654299/f88c3182-41ac-4257-932e-0243573132e3)

**Comment by sdatkinson** [comment]
The red circles next to the files...

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/3cb8263c-cd28-43fd-9925-21f03f37014c)


...mean that they've failed to upload. Compare to what [I show in the tutorial video](https://youtu.be/uWXA5chH2G4?si=WiDHH6z0uyPa15HW&t=88): they show up under the file tree:

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/b048c108-36e2-4e00-86e5-74a06c7272fb)

I'm going to guess you're using Firefox (kind reminder to please fill out all the details when you file a bug report so I don't have to guess!); if you try using Chrome, you may find that the file upload dialog in Colab is a bit more stable (odd, I know, but I guess it makes sense that Google would work well with Google 😉).

Let me know if this does it.

**Comment by warpkwd** [comment]
@sdatkinson 
Thank you.
It worked fine with chrome.
