### ISSUE TITLE
[FEATURE] Directly load NAM files in Python for reamping

### ISSUE THREAD

**Issue by dimentorium** [sdatkinson/neural-amp-modeler#315]
Hello Steven,
first of all thanks for that brilliant project!
Maybe I am not finding the right function call (or I am too dumb), but wanted to check if its possible to load the .nam files directly in python for doing automated reamping of the models.
Would like to generate a dataset of different amp and IR combinations to do a feature extraction on the results and play around with umap or tsne if its possible to build a good visualisation/searching on a large set of amps.

Best regards
Phil

**Comment by sdatkinson** [comment]
Good question. Have a look at #233, which tracks this. There's a PR for loading weights for `WaveNet` that's been merged already which might get you some mileage in the short-term.

Going to close this as a duplicate and we can continue on the other Issue 👍🏻
