### ISSUE TITLE
Train using ROCm?

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#317]
Since there is no discussion section I post my question here.

Is it possible to use Pytorch and Tensorflow for ROCm to train NAM models? If so, does anyone have knowledge they can share on how to do this?

Regards.

**Comment by sdatkinson** [comment]
This should be possible on computers on which PyTorch's ROCm backend is already supported.  Have a look at [Start Locally | PyTorch](https://pytorch.org/get-started/locally/) to see more details.

**Comment by 38github** [comment]
I am trying it out now and will report back if I am successful.
