### ISSUE TITLE
Preview Model

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/neural-amp-modeler#319]
When training a model I usually go for 600 epochs to get maximum accuracy. There are times where I would like to see if the model is going to turn out the way I expect it to. It would be super helpful for me to be able to hit some sort of a "preview" button that renders the model where the training process is currently, and then continues the training to the specified epochs number and renders that one at the end also. 

Or perhaps the number could be specified in the trainer before starting the training. "Preview Epochs" set to for example 100 and "Final Epochs" set to 600. Models are rendered at both 100 and 600 epochs. 

If that is a lot of time to make a small feature, no worries. But figured it can't hurt to ask.

**Comment by sdatkinson** [comment]
The three best checkpoints are always saved. As a workaround, you could [export](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/export/main.py) one of those?

**Comment by jaredbehrens** [comment]
I am not quite sure how to do that since I have been spoiled by the GUI
version. Are you able to still send commands in the CLI when the training
process was started from the GUI?

**Comment by sdatkinson** [comment]
I'd open a second terminal and do it there.

I'd also recommend copy-pasting the checkpoint you want to export since it may get deleted in favor of a better one as the trainer continues.

**Comment by jaredbehrens** [comment]
Okay, I will try this. Since all this functionality exists already you can
close the request.
