### ISSUE TITLE
[BUG] Checks not possible sometimes,

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#320]
With some distortion the script is not able to automatically check that the audio is correct. I wonder if this might be because the intro and outro clicks have been to altered? Can this be solved by having more clicks, some that are a lot more quiet to avoid too much alteration and maybe have some of the clicks also going into negative phase instead of only positive?

**Comment by sdatkinson** [comment]
Can you share an example for this Issue? I prefer to make Issues have a clear condition for resolution instead of "sometimes". 

Thanks!

**Comment by 38github** [comment]
> Can you share an example for this Issue? I prefer to make Issues have a clear condition for resolution instead of "sometimes".

Sure thing. I will find the captures and get back to you.

**Comment by 38github** [comment]
> Can you share an example for this Issue? I prefer to make Issues have a clear condition for resolution instead of "sometimes".

Here is one. I will keep looking for more.

[ty-rant_dumb_hunny_boost_on_gain_3o_tone_12o.zip](https://github.com/sdatkinson/neural-amp-modeler/files/13114148/ty-rant_dumb_hunny_boost_on_gain_3o_tone_12o.zip)

**Comment by sdatkinson** [comment]
Fixed by #330 , which gets rid of stopping training because this check failed.

**Comment by sdatkinson** [comment]
(It's not that it _can't_ check that the audio is correct--it's that it _did_ check, and the check failed 🙂)
