### ISSUE TITLE
PyTorch CUDA version in `environment_gpu.yml` is out of date

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#341]
CUDA 11.7 is no longer a recommended version [by PyTorch](https://pytorch.org/get-started/locally/); 11.8 is the "old version" now:
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/12240186/fc8a981a-1a46-4468-988b-8655ee79af0c)

Let's bump up to 12.1!

This may require people to update their drivers, and it'll be worth having some hints in the `environment_gpu.ymnl` and `README.md`.

I may also need to update the [installation video](https://www.youtube.com/watch?v=DFWVvJx1Cfs).

**Comment by hmollercl** [comment]
This shoud be also change here: https://neural-amp-modeler.readthedocs.io/en/latest/installation.html which I assume comes from here https://github.com/sdatkinson/neural-amp-modeler/blob/d04fa0ca76e30c2f558f2208b36d8542e9c0290b/docs/source/installation.rst#L14

**Comment by hmollercl** [comment]
https://github.com/sdatkinson/neural-amp-modeler/pull/478
