### ISSUE TITLE
Confusing error message when validation should be OK?

### ISSUE THREAD

**Issue by erikgrahn13** [sdatkinson/neural-amp-modeler#347]
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/21140674/5586d14b-a4db-406a-b445-c8e9234d991a)

Hello! Any idea what i might be doing wrong when getting this error message when trying to train my model?
 "Input provided isn't silent for at least 19200 samples before the starting index. Responses to this non-silent input may leak into the dataset"

The first track is the output.wav and the second track is the V2_0_0.wav. As you can see the marker is placed at sample 24022 and only silence before (have analyzed it) the first transient/blip occurs. Why does it complain that it isn't silent for 19200 samples?

**Comment by sdatkinson** [comment]
I need more info.

* What are you running? The GUI trainer?
* What is the full output from the program? The sniper you gave doesn't have the information I need.
* Are you using an original, unmodified v2_0_0.wav? I suspect not?

**Comment by erikgrahn13** [comment]
Yeah sorry man for not providing more.

Im not using the GUI trainer. I use the scripts so I run this:
```
python bin/train/main.py \
bin/train/inputs/data/single_pair.json \
bin/train/inputs/models/wavenet.json \
bin/train/inputs/learning/default.json \
bin/train/outputs/MyAmp
```
I have modified the single_pair.json of course to point to my files.
The full output looks like this:
```
(nam) C:\Users\erikg\Development\neural-amp-modeler>python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/wavenet.json bin/train/inputs/learning/default.json bin/train/outputs/MyAmp
Traceback (most recent call last):
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 241, in <module>
    main(parser.parse_args())
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 163, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 188, in main_inner
    dataset_validation = init_dataset(data_config, Split.VALIDATION)
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 793, in init_dataset
    return init({**common, **base_config})
  File "c:\users\erikg\development\neural-amp-modeler\nam\_core.py", line 11, in init_from_config
    return cls(**cls.parse_config(config))
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 285, in __init__
    self._validate_preceding_silence(
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 582, in _validate_preceding_silence
    raise XYError(
nam.data.XYError: Input provided isn't silent for at least 19200 samples before the starting index. Responses to this non-silent input may leak into the dataset!
```

I am using the original v2_0_0.wav file. Have not modified it.

**Comment by erikgrahn13** [comment]
I did some debugging to check the first element of x (input signal).
`print(f'x0: {x[0]}')`

I added this in the beginning of parse_config method in the Dataset class
```
    @classmethod
    def parse_config(cls, config):
        x, x_wavinfo = wav_to_tensor(
            config["x_path"], info=True, rate=config.get("rate")
        )
        rate = x_wavinfo.rate
        print(f'x0: {x[0]}') <---------------- HERE!
        ...
```

I also did a clean download of v1_1_1.wav, v2_0_0.wav and v3_0_0.wav and ran the code for every file just to see the value of the first element of x.

Running with v1_1_1.wav as input file:
```
(nam) C:\Users\erikg\Development\neural-amp-modeler>python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/wavenet.json bin/train/inputs/learning/default.json bin/train/outputs/MyAmp
x0: 0.0    <----------------------------- LOG HERE!!!!
Traceback (most recent call last):
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 241, in <module>
    main(parser.parse_args())
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 163, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 187, in main_inner
    dataset_train = init_dataset(data_config, Split.TRAIN)
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 802, in init_dataset
    return init({**common, **base_config})
  File "c:\users\erikg\development\neural-amp-modeler\nam\_core.py", line 11, in init_from_config
    return cls(**cls.parse_config(config))
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 361, in parse_config
    print(f'y0: {y[0]}')
UnboundLocalError: local variable 'y' referenced before assignment
```

Running with v2_0_0.wav as input file:
```
(nam) C:\Users\erikg\Development\neural-amp-modeler>python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/wavenet.json bin/train/inputs/learning/default.json bin/train/outputs/MyAmp
x0: 1.1920928955078125e-07    <----------------------------- LOG HERE!!!!
Traceback (most recent call last):
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 241, in <module>
    main(parser.parse_args())
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 163, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 187, in main_inner
    dataset_train = init_dataset(data_config, Split.TRAIN)
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 802, in init_dataset
    return init({**common, **base_config})
  File "c:\users\erikg\development\neural-amp-modeler\nam\_core.py", line 11, in init_from_config
    return cls(**cls.parse_config(config))
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 361, in parse_config
    print(f'y0: {y[0]}')
UnboundLocalError: local variable 'y' referenced before assignment
```

Running with v3_0_0.wav as input file:
```
(nam) C:\Users\erikg\Development\neural-amp-modeler>python bin/train/main.py bin/train/inputs/data/single_pair.json bin/train/inputs/models/wavenet.json bin/train/inputs/learning/default.json bin/train/outputs/MyAmp
x0: 0.0    <----------------------------- LOG HERE!!!!
Traceback (most recent call last):
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 241, in <module>
    main(parser.parse_args())
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 163, in main
    main_inner(data_config, model_config, learning_config, outdir, args.no_show)
  File "C:\Users\erikg\Development\neural-amp-modeler\bin\train\main.py", line 187, in main_inner
    dataset_train = init_dataset(data_config, Split.TRAIN)
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 802, in init_dataset
    return init({**common, **base_config})
  File "c:\users\erikg\development\neural-amp-modeler\nam\_core.py", line 11, in init_from_config
    return cls(**cls.parse_config(config))
  File "c:\users\erikg\development\neural-amp-modeler\nam\data.py", line 361, in parse_config
    print(f'y0: {y[0]}')
UnboundLocalError: local variable 'y' referenced before assignment
```

For v1_1_1.wav and v3_0_0.wav i get that x[0] is 0.0
But for v2_0_0.wav the value that is outputed is  1.1920928955078125e-07 which is why the validation fails in later step.
I just download a new copy of the v2_0_0.wav file and pointed to that one in single_pair.json. So it seems the v2_0_0.wav is somehow corrupt? 😕

**Comment by 38github** [comment]
> I am using the original v2_0_0.wav file. Have not modified it.

I also use unmodified v2_0_0.wav and get the same message you do.

**Comment by sdatkinson** [comment]
Since you're using the CLI trainer, I also need your JSONs.

I suspect the problem is you're not setting `start` and `stop` for the training and (what's causing teh error here) validation splits appropriately.

**Comment by erikgrahn13** [comment]
This is my single_pair.json file. The only file I have modified

```
{
    "_notes": [
        "Dev note: Ensure that tests/test_bin/test_train/test_main.py's data is ",
        "representative of this!"
    ],
    "train": {
        "start": null,
        "stop": -432000,
        "ny": 8192
    },
    "validation": {
        "start": -432000,
        "stop": null,
        "ny": null
    },
    "common": {
        "x_path": "C:\\Users\\erikg\\Downloads\\v2_0_0 (2).wav",
        "y_path": "C:\\Users\\erikg\\OneDrive\\Skrivbord\\Music\\NAM\\Bounced Files\\NAM.wav",
        "delay": 0
    }
}
```

**Comment by 38github** [comment]
>         "x_path": "C:\\Users\\erikg\\Downloads\\v2_0_0 (2).wav",

The space in the filename maybe an issue?

**Comment by sdatkinson** [comment]
I see.

The values you have for `"start"` and `"stop"` aren't good. 432,000 samples is 9 seconds. That's in the middle of the second replicate of the validation signal in the v2_0_0.wav file--see [the info in `nam.train.core.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/aa2b2b8b85d09d79353ceae0daed208a9ebb51bc/nam/train/core.py#L246).

v2_0_0.wav, as the name implies, has breaking changes that mean that you can't handle it the same way as the "v1" files. 

---

Using the CLI trainer gives you the ability to customize training to a pretty extreme degree; the flip side is that it's on you to understand what you're asking it to do. In case you weren't aware, the training process splits that data into training and validation sets; the former is used to fit the model, and the latter is used to check the fitted model to make sure it works on new signals that it's never seen again--and it's that "unseen" data that the metrics like the ESR are reported. It also means that if you don't use the same validation data as the simplified trainers use, then the comparison isn't meaningful.

But since both splits are coming from the same audio file (the alternative is to reamp them separately), it's on you to make sure that the start of the split is quiet--otherwise if some huge noise happened just before the split's start, then it'd bleed into the split's output and there'd be no way to be able to predict it--which is what the warning is telling you.

Punchline: for the train split, you probably want `"stop": -960000` (20 seconds from the end of the file, i.e. 2:51), and for the validation split you want `"start": -960000` and `"stop": -528000` (11 seconds from the end, i.e. 3:00).

**Comment by sdatkinson** [comment]
Closing this since I haven't heard back; going to assume this did the trick.
