### ISSUE TITLE
[BUG] Cannot export working .nam model using console with default settings.

### ISSUE THREAD

**Issue by Dumppa** [sdatkinson/neural-amp-modeler#351]
Model trained with "out of the box" settings not exporting properly to nam model when making export through console. Model created this way makes atleast the standalone neuralampmodeler plugin crash.

1. Train a model with wavenet architecture, using "out of the box" settings through console. I used the official v3_0_0.wav as di file and reamped using that.
2. Export the model through console (conversion to nam)
3. Load model to neural amp modeler and it will crash when it tries to load the model (atleast the standalone version)

I did also training through GUI and then everything went smoothly. Im running the latest version of both neural amp modeler plugin and neural amp modeler itself (21.12.2023)

**Comment by sdatkinson** [comment]
Can you share the .nam that isn't working?

**Comment by Dumppa** [comment]
Sure, here you go: https://drive.google.com/file/d/1005ce6mzvf88g1QMlSAsZXSTOfLc67Px/view?usp=sharing

**Comment by honkkis** [comment]
Confirmed. Fixed by this after export. 

import json; y = json.load(open("model.nam", 'r'))
y['sample_rate']=48000
json.dump(y, open('model48.nam', 'w'))

**Comment by sdatkinson** [comment]
Ah, I see: the sample rate isn't store in the model during training--I see myself [it gets put back in _after_ loading the best checkpoint](https://github.com/sdatkinson/neural-amp-modeler/blob/a2f54f02050c6a87d313880b7f805c757f10e4f9/bin/train/main.py#L218).

Let me see about putting this as an attribute of the base net class that'll end up in the checkpoints.
