### ISSUE TITLE
.wav output from colab notebook

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/neural-amp-modeler#37]
Thanks for making the colab notebook available!

It would be really useful to have a section at the end of the notebook to run the trained model on an input .wav file and produce an output .wav for downloading. The input .wav could just be the validation .wav source, or even better an arbitrary uploaded .wav file.

**Comment by sdatkinson** [comment]
Hi!

Thanks for the suggestion, and thanks for letting me know that you find the Colab useful! It's helpful to get feedback on it :)

In he meantime, a workaround is you can use [bin/run.py](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/run.py). With the exception of the new LSTM models (whose PyTorch implementation lags a bit wrt the C++ implementation), the run time should be comparable to the length of the sample you're processing, even when running the model on CPU.

**Comment by mikeoliphant** [comment]
Thanks - I'll give that a try.

**Comment by mikeoliphant** [comment]
Closing this as it really isn't important given the current NAM plugin.
