### ISSUE TITLE
Model time-based effect error

### ISSUE THREAD

**Issue by slives-lab** [sdatkinson/neural-amp-modeler#370]
I'm wondering if NAM is capable of modeling effects (delay, etc). 

Delay wasn't provided; attempting to calibrate automatically...
Delays:
 Blip  1: -4
 Blip  2: -4
After aplying safety factor of 4, the final delay is -8
Plotting the delay for manual inspection...

V3 checks...
Replicate ESR is 0.25202629.
Validation replicates have a self-ESR of over 0.01. Your gear doesn't sound like itself when played twice!

Possible causes:
 * Your signal chain is too noisy.
 * There's a time-based effect (chorus, delay, reverb) turned on.
 * Some knob got moved while reamping.
 * You started reamping before the amp had time to warm up fully.
Failed checks!

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X                                                                          X
X                                WARNING:                                  X
X                                                                          X
X       You are ignoring the checks! Your model might turn out bad!        X
X                                                                          X
X                              I warned you!                               X
X                                                                          X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by sdatkinson** [comment]
It's not set up to try to do that.

According to the eye message you shared, it looks like your gear doesn't sound the same when the same signal is put through it twice?

**Comment by RavingEagle** [comment]
Hello Steve,
Congratulations, and thank you for NAM! 
Is it not possible to model an amp plug-in to use via NAM?
Thanks
