### ISSUE TITLE
Hearing a lot of full rigs lately that have aliasing

### ISSUE THREAD

**Issue by 38github** [sdatkinson/neural-amp-modeler#384]
On ToneHunt I have lately heard many full rig models with aliasing. Has something changed lately that might cause this?

**Comment by sdatkinson** [comment]
Nope.

If there's an example where you've got the data and it doesn't work well, then that's potentially interesting to me. But stuff that's just about what people are putting on ToneHunt is out-of-scope for Issues here.

**Comment by 38github** [comment]
Since there is no discussion section I opened an issues. My bad.

**Comment by sdatkinson** [comment]
You might want to discuss it on the ToneHunt Discord? Since this is(?) an issue with their content
