### ISSUE TITLE
[FEATURE] Bolder Text in the GUI Trainer

### ISSUE THREAD

**Issue by DomMcsweeney** [sdatkinson/neural-amp-modeler#388]
I thought it might be an idea to give the GUI trainer some attention - for some it might be visually unclear. 
The text being small, and the red colour isn't all that easy on the eye.
 
Not sure what to suggest but perhaps something could be worked out to make it more visible: 
Bolder / darker text? 

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/86134812/2b0ec1af-4456-41c7-9d5c-ccf46e9b4e11)

**Comment by sdatkinson** [comment]
I can definitely do darker.
