### ISSUE TITLE
[FEATURE] Add "Stop training if ESR equal to" option in GUI "Advanced options"

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#393]
Hey Steve,

Been training models in batches; some turn out pretty good in fewer epochs, others need more. 

It would be of great help if the GUI trainer could have an option that stops training the current model (and skips to the next one if more are lined up) if it's already at a "good-enough" quality level for the user running the training.

Something like a checkbox for "Stop training if ESR is equal to" and a field value where the user can input their desired ESR value like "0.015" etc. 

Thanks for taking the time to read this 😊

**Comment by sdatkinson** [comment]
Yep, I can do this by customizing [`EarlyStopping`](https://lightning.ai/docs/pytorch/stable/_modules/lightning/pytorch/callbacks/early_stopping.html#EarlyStopping).
