### ISSUE TITLE
[BUG] GUI Trainer - Advanced Settings - Clicking on (X) leaves all functions in main window greyed out

### ISSUE THREAD

**Issue by PippPriss** [sdatkinson/neural-amp-modeler#414]
When running the GUI Trainer, clicking in the Advanced Settings and exiting via the (X) symbol, you cannot choose any option anymore in the main menu, as it remains cvompletely greyed out. You can only close the Trainer instance and then reopen a new one.

Clicking on OK or Cancel on the other hand works fine, no issues. 
Tested on Windows 10, latest version.

1. Open GUI Trainer
2. Click Advanced Settings
3. Close the pop-up window via (X) button
4. Main window is now greyed out, nothing to do here.

**Expected behavior**
Clicking the (X) of the Advanced Settings pop-up should free up all elements of the main window.

**Screenshots**
***Cannot do screenshots because ongoing NAM trainings, sorry!***

**Desktop (please complete the following information):**
 - Windows 10
 - Local GUI Trainer
 - v0.8.3

**Additional context**
Has been confirmed by other users in the facebook group revolving around NAM.

**Comment by sdatkinson** [comment]
Thanks! On it
