### ISSUE TITLE
`core.py`: Stop deprecated use of `start` and `stop` when initializing data sets

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#424]
Use `start_samples`, `stop_samples` instead.

**Comment by yonMaor** [comment]
If possible I'd like to tackle this issue. 
Any other information I should know considering that this is my first time working on this project?

**Comment by sdatkinson** [comment]
When you're done, make a PR and the automatic testing should make sure things are working as expected.

**Comment by yonMaor** [comment]
Which start/stop are you referring to? 
I'm seeing a lot of these exactly, but as arguments only as part of dictionary keys in validation/train kwargs.

**Comment by sdatkinson** [comment]
I'm not sure off the top of my head.

Basically, find anything in [`core.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/nam/train/core.py) that [initializes a `Dataset`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L235) using the [`start`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L241) and [`stop`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L242) arguments, and have it instead use [`start_samples`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L243) and [`stop_samples`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L244) instead.

I'd recommend doing it by dropping a breakpoint on like [line 300](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L300) then looking at the stack to see where it came from.

It'll _probably_ often be via [`init_dataset`](https://github.com/sdatkinson/neural-amp-modeler/blob/825b810545516ce4556ba4e6cbde9f86641cb37b/nam/data.py#L771).

Does this help?

**Comment by yonMaor** [comment]
Do you have any instructions on how to run the code?

**Comment by yonMaor** [comment]
Is it possible that these parameters are only explicitly written in the single_pair.json and two_pairs.json files? 
Digging around a bit that's where I've been able to find them
