### ISSUE TITLE
[BUG] nam-full: error

### ISSUE THREAD

**Issue by giacomopas** [sdatkinson/neural-amp-modeler#447]
Hello,
I updated as per the release notes using:
> pip install --upgrade neural-amp-modeler

The nam command runs fine and the GUI opens. However, the nam-full command displays this error:

![Screenshot_2](https://github.com/user-attachments/assets/ab2a3613-4f2b-4c43-9de7-d496ab774c35)

From what I understood, the only required step was running the update command line. What am I missing or what could be wrong?

**Comment by sdatkinson** [comment]
That's not an error. It's telling you how to use it.

Have a look at the tutorial here: https://neural-amp-modeler.readthedocs.io/en/latest/tutorials/full.html
