### ISSUE TITLE
[FEATURE] NPU support

### ISSUE THREAD

**Issue by novikov-alexander** [sdatkinson/neural-amp-modeler#451]
I'm planning to upgrade my laptop and I'm curious is NPU support is planned for Neural Amp Modeller?

Thank you

**Comment by sdatkinson** [comment]
I'll have the trainer will support any accelerator that's supported by PyTorch Lightning.

As far as running real-time models, that's [NeuralAmpModelerCore](https://github.com/sdatkinson/NeuralAmpModelerCore)'s scope, and I haven't looked into NPU support there. At a glance, it doesn't seem worth it to me--the typical model for NAM is super-tiny.
