### ISSUE TITLE
[FEATURE] Overtrain/overfit limiters

### ISSUE THREAD

**Issue by MarcoRavich** [sdatkinson/neural-amp-modeler#456]
Hi there,
I'm honestly not sure if these features have already been implemented in NAM (if so, suddently close this issue, sorry), but it would be extremely useful to have a more efficient learning - as @IAHispano managed to do in their [Applio](https://github.com/IAHispano/Applio#readme) for example - if possible.

Some interesting articles about:
- [How to Guide: Overcoming overfitting in your ML models](https://predibase.com/blog/how-to-guide-overcoming-overfitting-in-your-ml-models);
- [A Gentle Introduction to Early Stopping to Avoid Overtraining Neural Networks](https://machinelearningmastery.com/early-stopping-to-avoid-overtraining-neural-network-models/);
- [Overfitting in Machine Learning: What It Is and How to Prevent It](https://elitedatascience.com/overfitting-in-machine-learning);
- ...

Hope that inspires !

**Comment by sdatkinson** [comment]
Hi there.

The trainer already uses checkpointing. See here: 
* https://github.com/sdatkinson/neural-amp-modeler/blob/619fb4dcaed62aac6baaf207b283ff3e9c92851d/nam/train/core.py#L1236
* https://github.com/sdatkinson/neural-amp-modeler/blob/619fb4dcaed62aac6baaf207b283ff3e9c92851d/nam/train/core.py#L1431
