### ISSUE TITLE
Input V3_0_0.wav not recognized

### ISSUE THREAD

**Issue by alikit** [sdatkinson/neural-amp-modeler#458]
Now training /Users/mixondaw/Desktop/output.wav
Strong hash: 36cd1af62985c2fac3e654333e36431e
Provided input file /Users/mixondaw/Downloads/v3_0_0.wav does not strong-match any known standard input files.
Falling back to weak-matching...
Weak hashes:
 Start (v1) : 9f36f71c6a76d2c36144e8cd8a34f5ef
 End (v1)   : 8458126969a3f9d8e19a53554eb1fd52
 Start (v2) : 8f7b431a879e229d733d220442a8df16
 End (v2)   : 364b536bcd4f74d8e13c42d20c095861

Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nam/train/gui.py", line 351, in _train
    trained_model = core.train(
                    ^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nam/train/core.py", line 833, in train
    input_version, strong_match = _detect_input_version(input_path)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nam/train/core.py", line 153, in _detect_input_version
    raise ValueError(
ValueError: Input file at /Users/mixondaw/Downloads/v3_0_0.wav cannot be recognized as any known version!

**Comment by sdatkinson** [comment]
Strange: the hash there matches the strong hash for v3_0_0.wav, so it should be recognized.

Can you run the tests?

**Comment by sdatkinson** [comment]
These tests in specific:
https://github.com/sdatkinson/neural-amp-modeler/blob/6a610ec9cb89f47d57b2d1d30779c21a642e649b/tests/test_nam/test_train/test_core.py#L46

If they don't pass, then something is odd with your setup--they pass on my computer. If they do pass, then that would be _very_ odd.

**Comment by sdatkinson** [comment]
Aha, I see the problem: your trainer is out of date: where it's computing weak hashes...

<img width="355" alt="image" src="https://github.com/user-attachments/assets/72d3f64e-061d-4eed-8df2-19dd5f700e38">

...I see that it's only computing for v1 and v2, but not v3. That's probably because you're out of date.

Update with
```
pip install --upgrade neural-amp-modeler
```
and you should be set!
