### ISSUE TITLE
[BUG] No Amp Models??

### ISSUE THREAD

**Issue by Benji1308** [sdatkinson/neural-amp-modeler#471]
Hello,

im New to NAM and im very interested to play it in my DAW or as a Stanalone Version, but sadly i dont have any Amp Models or Profiles that are should be included directly after i downloaded it??

Pls help, idk what to do.

Love to hear some Answers and Results!!!

Thank You!

**Comment by 38github** [comment]
There are a few public repositories available.

https://www.tonehunt.org/
http://coginthemachine.ddns.net/mnt/nam/

**Comment by Benji1308** [comment]
Hello Atkinson,

thank you, the Tonehub one was very helpful.

Kind Regards

Am Di., 24. Sept. 2024 um 09:24 Uhr schrieb 38github <
***@***.***>:

**Comment by sdatkinson** [comment]
It looks like you're looking for [NeuralAmpModelerPlugin](), but as it just so happens, this is the repository with the code that _makes_ the models!

You should give it a try! 🙂

**Comment by Benji1308** [comment]
Thank you for helping me, it worked!

kind regards

Steven Atkinson ***@***.***> schrieb am Fr. 27. Sep. 2024 um
17:40:
