### ISSUE TITLE
[FEATURE] Checkbox to enable/disable NAM model export for each epoch

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#481]
Been training some batch models in the latest version & couldn't help but notice the recent feature to create a nam model after each epoch eats up a bit of extra processing time.

Could we have a checkbox (maybe underneath the "Save ESR plot automatically") in the GUI version to toggle this feature ON and OFF? 

Thank you!

**Comment by sdatkinson** [comment]
I don't think I'll be adding that myself, but adding options like this is exactly what [extensions](https://github.com/sdatkinson/neural-amp-modeler/issues/440) are good for.
