### ISSUE TITLE
Non-unity input gain for inputs

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#49]
If I reamp a training signal, but the output from my interface is louder than unity gain, then that could allow me to model how the amp reacts for inputs beyond +/- 1.  This could be useful for getting a realistic response when e.g. the input is hit with a really hot boost.  We'd also then want to multiply up the signal as it's being fed to the amp to reflect what the amp "really saw."

This might be incorporated as an optional parameter in the data set configuration JSON.

**Comment by jaredbehrens** [comment]
Would it be possible to also apply this concept to a knob? A capture that has a realistic gain knob maybe?

**Comment by sdatkinson** [comment]
> Would it be possible to also apply this concept to a knob? A capture that has a realistic gain knob maybe?

Different concept there 🙂 I'm going to close this since this is about rescaling the input signal as data for the model
