### ISSUE TITLE
data folders for params model checkpoint for pycharm don't work

### ISSUE THREAD

**Issue by jamsden** [sdatkinson/neural-amp-modeler#5]
`model.load_state_dict(torch.load(args.params))`

gets 

`IsADirectoryError: [Errno 21] Is a directory: 'data/emissary'`

Do these model checkpoints need to be updated for the pycharm version? Do you happen to have the samples?

**Comment by sdatkinson** [comment]
Hi, Jim.

Can i get more info on where exactly this is happening? Nothing in here should depend on what IDE you like to use.

**Comment by jamsden** [comment]
I'm trying to run reamp.py with the data that's in the data folder:

`python reamp.py architectures/fc_32_32_32.json data/emissary /Users/jamsden/temp/Guitar1_1.wav --output /Users/jamsden/temp/Guitar1_1-processed.wav`

torch.load(args.params) fails on data/emissary. That data looks old, i.e., the model hasn't been updated using the new PyTorch framework.

**Comment by jamsden** [comment]
I thought I could get reamp.py working on your sample model before creating my own amp model. I have an early '60's Tremolux amp I want to capture.

**Comment by sdatkinson** [comment]
Closing this as I ended up ripping up the old way of handling data in v0.2.
