### ISSUE TITLE
[BREAKING] Use imports into private scope.

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#510]
There's a lot of imports across the package into public scope, and many aren't intentional.

To take a random example: 
https://github.com/sdatkinson/neural-amp-modeler/blob/f2c3ff91c94bd06b19ed3e0052ade1e4dea02391/nam/cli.py#L80

No one is (or should be!) doing `from nam.cli import json` instead of `import json`.

This is a bit of a silly example, but it's an opportunity to be more careful about what's intended to be exposed and what's not. For example, VScode will pick up `json` from that module and volunteer to use it elsewhere--which isn't intended, but one can't fault a downstream user for not being careful. More subtle examples involve the classes, etc, that _are_ introduced by the package.

So this is pretty nitty, but it'd be a nice way to make the code in here even better. I've thougth about this for a while, but I saw it recently in PyTorch's source code and thought it was a nice thing to do (and proof that I wasn't alone in this).

So for example, this Issue recommends refactoring the above to `import json as _json`.

Marking as a "good first issue" since this is a pretty general exercise to do and doesn't require much special knowledge about NAM.

**Comment by zghannam** [comment]
So if I'm understanding correctly, something like "import abc" would be changed to "import abc as _abc" and so on. Just to make sure, would this also include specific imports like "from pathlib import Path" to "from pathlib import Path as _Path" or for classes from the package like "from .base import BaseNet" to "from .base import BaseNet as _BaseNet"?

**Comment by sdatkinson** [comment]
@zghannam

> So if I'm understanding correctly, something like "import abc" would be changed to "import abc as _abc" and so on.

Correct

> Was also wondering if this should be done for every part of the repository

The contents of the package proper ([nam/](https://github.com/sdatkinson/neural-amp-modeler/tree/main/nam)) are what are most important since that's what others would build on top of.

**Comment by zghannam** [comment]
And should this be done for third party imports (i.e. "import torch as _torch") as well as specific imports from libraries (i.e. "from enum import Enum as _Enum")? Same thing with classes from within the nam package? Thanks for the info!
