### ISSUE TITLE
[BUG] Neural Amp Modeler falling back to CPU instead of using the GPU

### ISSUE THREAD

**Issue by binky100** [sdatkinson/neural-amp-modeler#521]
I followed your instructions for installing nam found here : https://neural-amp-modeler.readthedocs.io/en/latest/installation.html and I am still getting the error that no gpu is detected and that the nam local trainer is going to fall back to the CPU. From the research I did my GPU (nvidia GTX1650) should work but for some reason the nam trainer keeps falling back to the CPU. Can you please help me figure out what is going wrong?

**Comment by binky100** [comment]
You can close this after clearing the past installation attempt and restarting nam is working at full speed now and using my gpu as intended. Thank you for your patience.

**Comment by sdatkinson** [comment]
@binky100 glad to hear it.

Any idea what the problem was in the end?
