### ISSUE TITLE
Comile VST plugin to load trained file .h

### ISSUE THREAD

**Issue by fewtubefx** [sdatkinson/neural-amp-modeler#54]
Is it possible to compile VST plugin with loading option. Not to compile new plugins every time.

**Comment by sdatkinson** [comment]
Hi! Thanks for the suggestion--in fact this is exactly the plan for the next version of the plugin!

Stay tuned over at https://github.com/sdatkinson/iPlug2 where this will be released.

Closing this issue here since the code in this repo is already good to go 👍
