### ISSUE TITLE
No GPU backend

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/neural-amp-modeler#64]
I cannot seem to get the script to recognize my GPU. I have a GTX 1660 - Running on Windows 10.

![image](https://user-images.githubusercontent.com/120538163/208269112-cfdf9a95-e88d-46e3-bd4b-89f3bdf6d099.png)

**Comment by jaredbehrens** [comment]
It was an issue on my end, resolved.

**Comment by sdatkinson** [comment]
See also #65, #67
