### ISSUE TITLE
GUI Trainer

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#68]
For desktop installs, a GUI version of the trainer would be nice.

**Comment by 2-dor** [comment]
> For desktop installs, a GUI version of the trainer would be nice.

This would be great especially now that more people are starting to look at NAM. 
Even without a GUI trainer, maybe some new jupyter notebooks for CPU and GPU training would do just fine.

**Comment by AriKuorikoski** [comment]
How about simplified command line trainer for starters? 

Now one needs to go and tweak config files and pass reference of the config files for the python script. Perhaps could have named sets of config files (declare one as default) and then let user to pass the set name to main. Also let user to override certain pre-selected variables from the config files, like the source and target files.
