### ISSUE TITLE
[FEATURE] Cab modeling

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/neural-amp-modeler#85]
Implement amp & cab modeling.

Consider using a causal [Wiener filter](https://en.wikipedia.org/wiki/Wiener_filter) to estimate the cab quickly.

**Comment by ServusJon** [comment]
oh yes!

**Comment by ServusJon** [comment]
bump :)

**Comment by musicalentropy** [comment]
What do you mean with cab modeling?

**Comment by ServusJon** [comment]
Please @sdatkinson look into this :)

**Comment by ServusJon** [comment]
I am so excited for this one!
