### ISSUE TITLE
[FEATURE] IR scrolling buttons

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#86]
Just a small quality of life update if possible: add 2 buttons to scroll through IRs within the current IR's folder. 

Thank you! \m/

**Comment by sdatkinson** [comment]
Hi!

This is the trainer repo; can you leave this on [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin) so I don't lose track of it?

Thanks!
