### ISSUE TITLE
Allow bulk training

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#88]
Allow to bulk upload multiple files with corresponding amp names that will be transferred to the .nam file

**Comment by sdatkinson** [comment]
I like this suggestion, but I suspect you're thinking of doing this with Easy Mode on Colab.

Unfortunately, Colab will time out after a while, and I'd hate for folks to discover that the hard way. So if I were to do this, I'd probably prioritize something that folks using their personal PCs could use. (There's also the paid Colab tier, but I'd worry that prioritizing that use case would be bad for most people.)

If you're able to and interested in trying out something on your personal computer, we might explore that?

**Comment by 2-dor** [comment]
> I like this suggestion, but I suspect you're thinking of doing this with Easy Mode on Colab.
> 
> Unfortunately, Colab will time out after a while, and I'd hate for folks to discover that the hard way. So if I were to do this, I'd probably prioritize something that folks using their personal PCs could use. (There's also the paid Colab tier, but I'd worry that prioritizing that use case would be bad for most people.)
> 
> If you're able to and interested in trying out something on your personal computer, we might explore that?

I'd love to have this available... together with a UI :D

**Comment by sdatkinson** [comment]
This is in the GUI trainer :)
