### ISSUE TITLE
Installation on Apple M1 

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#89]
I downloaded the repo on my machine. I installed Conda.

If I run:
`conda env create -f environment_cpu.yml
`

It always tells me:
EnvironmentFileNotFound

What am I missing?

**Comment by 2-dor** [comment]
> I downloaded the repo on my machine. I installed Conda.
> 
> If I run: `conda env create -f environment_cpu.yml `
> 
> It always tells me: EnvironmentFileNotFound
> 
> What am I missing?

You'll need to navigate to the "neural-amp-modeler" folder to get that command to run

**Comment by ServusJon** [comment]
I am in that folder... I managed to run it by just using: 
`conda env create -f environment.yml `
