### ISSUE TITLE
[FEATURE] Local training and nVidia Tensor cores?

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#92]
While running the NAM modeler / trainer locally on an RTX capable card, torch throws back a message stating the Tensor cores may be better utilized. Not sure if this is a valid lead / would be something that could help training times or accuracy; just thought I'd list it here as some folks have asked about it in the Facebook group.
![image](https://user-images.githubusercontent.com/125308373/219172101-d7cac89a-3b8a-4fac-94d0-07e26998dd16.png)

**Comment by 2-dor** [comment]
Doesn't seem to make any difference if that command gets added to a training run. 
![image](https://user-images.githubusercontent.com/125308373/219206059-72837ff4-51f1-4662-9089-165e399bf196.png)
ESR is pretty much still the same for the same epochs

**Comment by sdatkinson** [comment]
I haven't looked into this yet.  My hunch is that it won't be super-useful, but it might give things a small boost.

If anyone wants to do some experiments, see what happens, and PR something because of it, then I'd be interested to see what they find. But, it's not a priority for me to look into personally.

**Comment by rossbalch** [comment]
I edited main.py on the terminal based trainer just under where the torch seed it set. On a Nvidia A10 it didn't seem to make any difference, the average epoch time was still 16seconds before and after. I'm hoping to test an A100 soon, with more cores available it might stack up there. Either way it's super simple update, just one line of code. If tensor cores aren't found torch defaults back to highest anyway.
torch.set_float32_matmul_precision('high')

**Comment by sdatkinson** [comment]
Seems there's not an action item here, so closing
