### ISSUE TITLE
MisconfigurationException: No supported gpu backend found!

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#94]
Using my Apple M1 machine and the "easy_colab.ipynb"

`MisconfigurationException Traceback (most recent call last)
Cell In[2], line 2
1 get_ipython().run_line_magic('tensorboard', '--logdir /content/lightning_logs')
----> 2 run(
3 epochs=100,
4 architecture="standard" # standard, lite, feather
5 )

File ~/opt/anaconda3/envs/nam/lib/python3.10/site-packages/nam/train/colab.py:363, in run(epochs, delay, architecture, lr, lr_decay, seed)
360 train_dataloader = DataLoader(dataset_train, **learning_config["train_dataloader"])
361 val_dataloader = DataLoader(dataset_validation, **learning_config["val_dataloader"])
--> 363 trainer = pl.Trainer(
364 callbacks=[
365 pl.callbacks.model_checkpoint.ModelCheckpoint(
366 filename="checkpoint_best_{epoch:04d}{step}{ESR:.4f}{MSE:.3e}",
367 save_top_k=3,
368 monitor="val_loss",
369 every_n_epochs=1,
370 ),
371 pl.callbacks.model_checkpoint.ModelCheckpoint(
372 filename="checkpoint_last{epoch:04d}_{step}", every_n_epochs=1
373 ),
374 ],
375 **learning_config["trainer"],
376 )
377 trainer.fit(model, train_dataloader, val_dataloader)
379 # Go to best checkpoint

File ~/opt/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py:348, in _defaults_from_env_vars..insert_env_defaults(self, *args, **kwargs)
345 kwargs = dict(list(env_variables.items()) + list(kwargs.items()))
347 # all args were already moved to kwargs
--> 348 return fn(self, **kwargs)

File ~/opt/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:420, in Trainer.init(self, logger, enable_checkpointing, callbacks, default_root_dir, gradient_clip_val, gradient_clip_algorithm, num_nodes, num_processes, devices, gpus, auto_select_gpus, tpu_cores, ipus, enable_progress_bar, overfit_batches, track_grad_norm, check_val_every_n_epoch, fast_dev_run, accumulate_grad_batches, max_epochs, min_epochs, max_steps, min_steps, max_time, limit_train_batches, limit_val_batches, limit_test_batches, limit_predict_batches, val_check_interval, log_every_n_steps, accelerator, strategy, sync_batchnorm, precision, enable_model_summary, num_sanity_val_steps, resume_from_checkpoint, profiler, benchmark, deterministic, reload_dataloaders_every_n_epochs, auto_lr_find, replace_sampler_ddp, detect_anomaly, auto_scale_batch_size, plugins, amp_backend, amp_level, move_metrics_to_cpu, multiple_trainloader_mode, inference_mode)
417 # init connectors
418 self._data_connector = DataConnector(self, multiple_trainloader_mode)
--> 420 self._accelerator_connector = AcceleratorConnector(
421 num_processes=num_processes,
422 devices=devices,
423 tpu_cores=tpu_cores,
424 ipus=ipus,
425 accelerator=accelerator,
426 strategy=strategy,
427 gpus=gpus,
428 num_nodes=num_nodes,
429 sync_batchnorm=sync_batchnorm,
430 benchmark=benchmark,
431 replace_sampler_ddp=replace_sampler_ddp,
432 deterministic=deterministic,
433 auto_select_gpus=auto_select_gpus,
434 precision=precision,
435 amp_type=amp_backend,
436 amp_level=amp_level,
437 plugins=plugins,
438 )
439 self._logger_connector = LoggerConnector(self)
440 self._callback_connector = CallbackConnector(self)

File ~/opt/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:202, in AcceleratorConnector.init(self, devices, num_nodes, accelerator, strategy, plugins, precision, amp_type, amp_level, sync_batchnorm, benchmark, replace_sampler_ddp, deterministic, auto_select_gpus, num_processes, tpu_cores, ipus, gpus)
200 self._accelerator_flag = self._choose_auto_accelerator()
201 elif self._accelerator_flag == "gpu":
--> 202 self._accelerator_flag = self._choose_gpu_accelerator_backend()
204 self._set_parallel_devices_and_init_accelerator()
206 # 3. Instantiate ClusterEnvironment

File ~/opt/anaconda3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:537, in AcceleratorConnector._choose_gpu_accelerator_backend()
534 if CUDAAccelerator.is_available():
535 return "cuda"
--> 537 raise MisconfigurationException("No supported gpu backend found!")

MisconfigurationException: No supported gpu backend found!`

Any hints @sdatkinson ?

**Comment by vossenv** [comment]
Do you have an nvidia card and installed NVCC?

**Comment by ServusJon** [comment]
It’s an Apple m1 with an Apple CardAm 17.02.2023 um 08:12 schrieb vossen ***@***.***>:﻿
Do you have an nvidia card and installed NVCC?

**Comment by ServusJon** [comment]
i would like to run it in CPU MODE Am 17.02.2023 um 08:23 schrieb Jonathan Arnold ***@***.***>:﻿It’s an Apple m1 with an Apple CardAm 17.02.2023 um 08:12 schrieb vossen ***@***.***>:﻿
Do you have an nvidia card and installed NVCC?

**Comment by sdatkinson** [comment]
[`easy_colab.ipynb`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/easy_colab.ipynb) is meant for use on Google Colab, where the runtime can be configured to include a GPU.

For training on a local machine, the current recommended way is to use [`bin/train/main.py`](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/main.py), which can be configured using the JSON files under [`bin/train/inputs/`](https://github.com/sdatkinson/neural-amp-modeler/tree/main/bin/train/inputs).

For configuring the device used (CPU, GPU, etc), [bin/train/inputs/learning/default.json](https://github.com/sdatkinson/neural-amp-modeler/blob/main/bin/train/inputs/learning/default.json#L12) can be configured.  The contents of this file are provided to the PyTorch Lightning Trainer.  See [its documentation](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html) for what options are available.

For CPU training, you can set `"gpus": 0`.
