### ISSUE TITLE
[FEATURE] Noise gate in between AMP and IR sections (sidechained to input)

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/neural-amp-modeler#95]
If there's any room for a noise gate in the next releases, hoping one could be implemented in between the AMP and IR blocks but sidechained to the Input.

**Comment by sdatkinson** [comment]
This should go under [NeuralAmpModelerPlugin](https://github.com/sdatkinson/NeuralAmpModelerPlugin)

[It's implemented](https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/65) and should be in the next release 😄
