### ISSUE TITLE
Normalize output.wav 

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/neural-amp-modeler#99]
I sometimes forget normalizing my output.wav which results in higher noise floor and less body. Can we normalize it automatically after uploading for training?

**Comment by 2-dor** [comment]
> I sometimes forget normalizing my output.wav which results in higher noise floor and less body. Can we normalize it automatically after uploading for training?

Hey - what level do you normalize to and what do you go for? True Peak etc?

**Comment by ServusJon** [comment]
I use the build in logic normalizing on export. Not sure what it’s using. But I have also used true peak -0.01

**Comment by sdatkinson** [comment]
Are you looking for models to all be the same loudness when loaded up? If so, that'd be #10.

Adjusting the level of the recorded `output.wav` after you've reamped won't affect the signal-to-noise ratio--they're stuck together in your recording.

**Comment by ServusJon** [comment]
ah ok. Then i am cool with #10
